package com.ayue.sp.db.po;

import java.util.Date;

public class AdvertRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_record.id
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_record.picture_url
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    private String pictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_record.comment
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_record.start_time
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_record.end_time
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_record.type
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_record.type
     *
     * @return the value of advert_record.id
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public Integer getType() {
        return type;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_record.type
     *
     * @param type the value for advert_record.type
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_record.id
     *
     * @return the value of advert_record.id
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_record.id
     *
     * @param id the value for advert_record.id
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_record.picture_url
     *
     * @return the value of advert_record.picture_url
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_record.picture_url
     *
     * @param pictureUrl the value for advert_record.picture_url
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_record.comment
     *
     * @return the value of advert_record.comment
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_record.comment
     *
     * @param comment the value for advert_record.comment
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_record.start_time
     *
     * @return the value of advert_record.start_time
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_record.start_time
     *
     * @param startTime the value for advert_record.start_time
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_record.end_time
     *
     * @return the value of advert_record.end_time
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_record.end_time
     *
     * @param endTime the value for advert_record.end_time
     *
     * @mbg.generated Fri Oct 09 11:49:48 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}