package com.ayue.sp.db.po;

import java.util.Date;

public class Answer {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.question_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer questionId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String content;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.picture_url
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String pictureUrl;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer agreeCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.comment_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer commentCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.forward_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer forwardCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.click_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer clickCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.ticket_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer ticketCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.city_address
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String cityAddress;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer status;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.direction
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer direction;

        private Integer adopt;

        private Integer ticket;

        private Integer charge;

        public Integer getCharge() {
                return charge;
        }

        public void setCharge(Integer charge) {
                this.charge = charge;
        }

        public Integer getTicket() {
                return ticket;
        }

        public void setTicket(Integer ticket) {
                this.ticket = ticket;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.id
         * @return  the value of answer.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getStatus() {
                return status;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.user_id
         * @param status  the value for answer.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setStatus(Integer status) {
                this.status = status;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.id
         * @return  the value of answer.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.id
         * @param id  the value for answer.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.user_id
         * @return  the value of answer.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.user_id
         * @param userId  the value for answer.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.question_id
         * @return  the value of answer.question_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getQuestionId() {
                return questionId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.question_id
         * @param questionId  the value for answer.question_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setQuestionId(Integer questionId) {
                this.questionId = questionId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.content
         * @return  the value of answer.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getContent() {
                return content;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.content
         * @param content  the value for answer.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setContent(String content) {
                this.content = content;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.picture_url
         * @return  the value of answer.picture_url
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getPictureUrl() {
                return pictureUrl;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.picture_url
         * @param pictureUrl  the value for answer.picture_url
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setPictureUrl(String pictureUrl) {
                this.pictureUrl = pictureUrl;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.agree_count
         * @return  the value of answer.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getAgreeCount() {
                return agreeCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.agree_count
         * @param agreeCount  the value for answer.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setAgreeCount(Integer agreeCount) {
                this.agreeCount = agreeCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.comment_count
         * @return  the value of answer.comment_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getCommentCount() {
                return commentCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.comment_count
         * @param commentCount  the value for answer.comment_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCommentCount(Integer commentCount) {
                this.commentCount = commentCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.forward_count
         * @return  the value of answer.forward_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getForwardCount() {
                return forwardCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.forward_count
         * @param forwardCount  the value for answer.forward_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setForwardCount(Integer forwardCount) {
                this.forwardCount = forwardCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.click_count
         * @return  the value of answer.click_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getClickCount() {
                return clickCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.click_count
         * @param clickCount  the value for answer.click_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setClickCount(Integer clickCount) {
                this.clickCount = clickCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.ticket_count
         * @return  the value of answer.ticket_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getTicketCount() {
                return ticketCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.ticket_count
         * @param ticketCount  the value for answer.ticket_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setTicketCount(Integer ticketCount) {
                this.ticketCount = ticketCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.city_address
         * @return  the value of answer.city_address
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getCityAddress() {
                return cityAddress;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.city_address
         * @param cityAddress  the value for answer.city_address
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCityAddress(String cityAddress) {
                this.cityAddress = cityAddress;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.create_time
         * @return  the value of answer.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.create_time
         * @param createTime  the value for answer.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }

        public Integer getDirection() {
                return direction;
        }

        public void setDirection(Integer direction) {
                this.direction = direction;
        }

        public Integer getAdopt() {
                return adopt;
        }

        public void setAdopt(Integer adopt) {
                this.adopt = adopt;
        }
}