package com.ayue.sp.db.po;

import java.util.Date;

public class Comment {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column comment.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column comment.answer_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer answerId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column comment.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column comment.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String content;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column comment.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer agreeCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column comment.reply_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer replyCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column comment.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer status;
        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.id
         * @return  the value of answer.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getStatus() {
                return status;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.user_id
         * @param status  the value for answer.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setStatus(Integer status) {
                this.status = status;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column comment.id
         * @return  the value of comment.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column comment.id
         * @param id  the value for comment.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column comment.answer_id
         * @return  the value of comment.answer_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getAnswerId() {
                return answerId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column comment.answer_id
         * @param answerId  the value for comment.answer_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setAnswerId(Integer answerId) {
                this.answerId = answerId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column comment.user_id
         * @return  the value of comment.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column comment.user_id
         * @param userId  the value for comment.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column comment.content
         * @return  the value of comment.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getContent() {
                return content;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column comment.content
         * @param content  the value for comment.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setContent(String content) {
                this.content = content;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column comment.agree_count
         * @return  the value of comment.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getAgreeCount() {
                return agreeCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column comment.agree_count
         * @param agreeCount  the value for comment.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setAgreeCount(Integer agreeCount) {
                this.agreeCount = agreeCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column comment.reply_count
         * @return  the value of comment.reply_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getReplyCount() {
                return replyCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column comment.reply_count
         * @param replyCount  the value for comment.reply_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setReplyCount(Integer replyCount) {
                this.replyCount = replyCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column comment.create_time
         * @return  the value of comment.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column comment.create_time
         * @param createTime  the value for comment.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}