package com.ayue.sp.db.po;

public class IdGeneratorRecorder {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column id_generator_recorder.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column id_generator_recorder.target_value
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer targetValue;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column id_generator_recorder.step_size
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer stepSize;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column id_generator_recorder.id
         * @return  the value of id_generator_recorder.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column id_generator_recorder.id
         * @param id  the value for id_generator_recorder.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setId(String id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column id_generator_recorder.target_value
         * @return  the value of id_generator_recorder.target_value
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getTargetValue() {
                return targetValue;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column id_generator_recorder.target_value
         * @param targetValue  the value for id_generator_recorder.target_value
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setTargetValue(Integer targetValue) {
                this.targetValue = targetValue;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column id_generator_recorder.step_size
         * @return  the value of id_generator_recorder.step_size
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getStepSize() {
                return stepSize;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column id_generator_recorder.step_size
         * @param stepSize  the value for id_generator_recorder.step_size
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setStepSize(Integer stepSize) {
                this.stepSize = stepSize;
        }
}