package com.ayue.sp.db.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuestionExample {
    /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        protected String orderByClause;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        protected boolean distinct;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        protected List<Criteria> oredCriteria;

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public QuestionExample() {
                oredCriteria = new ArrayList<Criteria>();
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setOrderByClause(String orderByClause) {
                this.orderByClause = orderByClause;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getOrderByClause() {
                return orderByClause;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setDistinct(boolean distinct) {
                this.distinct = distinct;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public boolean isDistinct() {
                return distinct;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public List<Criteria> getOredCriteria() {
                return oredCriteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void or(Criteria criteria) {
                oredCriteria.add(criteria);
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Criteria or() {
                Criteria criteria = createCriteriaInternal();
                oredCriteria.add(criteria);
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Criteria createCriteria() {
                Criteria criteria = createCriteriaInternal();
                if (oredCriteria.size() == 0) {
                        oredCriteria.add(criteria);
                }
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        protected Criteria createCriteriaInternal() {
                Criteria criteria = new Criteria();
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void clear() {
                oredCriteria.clear();
                orderByClause = null;
                distinct = false;
        }

        /**
         * This class was generated by MyBatis Generator. This class corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        protected abstract static class GeneratedCriteria {
                protected List<Criterion> criteria;

                protected GeneratedCriteria() {
                        super();
                        criteria = new ArrayList<Criterion>();
                }

                public boolean isValid() {
                        return criteria.size() > 0;
                }

                public List<Criterion> getAllCriteria() {
                        return criteria;
                }

                public List<Criterion> getCriteria() {
                        return criteria;
                }

                protected void addCriterion(String condition) {
                        if (condition == null) {
                                throw new RuntimeException("Value for condition cannot be null");
                        }
                        criteria.add(new Criterion(condition));
                }

                protected void addCriterion(String condition, Object value, String property) {
                        if (value == null) {
                                throw new RuntimeException("Value for " + property + " cannot be null");
                        }
                        criteria.add(new Criterion(condition, value));
                }

                protected void addCriterion(String condition, Object value1, Object value2, String property) {
                        if (value1 == null || value2 == null) {
                                throw new RuntimeException("Between values for " + property + " cannot be null");
                        }
                        criteria.add(new Criterion(condition, value1, value2));
                }

                public Criteria andIdIsNull() {
                        addCriterion("id is null");
                        return (Criteria) this;
                }

                public Criteria andIdIsNotNull() {
                        addCriterion("id is not null");
                        return (Criteria) this;
                }

                public Criteria andIdEqualTo(Integer value) {
                        addCriterion("id =", value, "id");
                        return (Criteria) this;
                }
                public Criteria andStatusEqualTo(Integer value) {
                        addCriterion("status =", value, "status");
                        return (Criteria) this;
                }

                public Criteria andIdNotEqualTo(Integer value) {
                        addCriterion("id <>", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdGreaterThan(Integer value) {
                        addCriterion("id >", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("id >=", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdLessThan(Integer value) {
                        addCriterion("id <", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdLessThanOrEqualTo(Integer value) {
                        addCriterion("id <=", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdIn(List<Integer> values) {
                        addCriterion("id in", values, "id");
                        return (Criteria) this;
                }

                public Criteria andIdNotIn(List<Integer> values) {
                        addCriterion("id not in", values, "id");
                        return (Criteria) this;
                }

                public Criteria andIdBetween(Integer value1, Integer value2) {
                        addCriterion("id between", value1, value2, "id");
                        return (Criteria) this;
                }

                public Criteria andIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("id not between", value1, value2, "id");
                        return (Criteria) this;
                }

                public Criteria andUserIdIsNull() {
                        addCriterion("user_id is null");
                        return (Criteria) this;
                }

                public Criteria andUserIdIsNotNull() {
                        addCriterion("user_id is not null");
                        return (Criteria) this;
                }

                public Criteria andUserIdEqualTo(Integer value) {
                        addCriterion("user_id =", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdNotEqualTo(Integer value) {
                        addCriterion("user_id <>", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdGreaterThan(Integer value) {
                        addCriterion("user_id >", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("user_id >=", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdLessThan(Integer value) {
                        addCriterion("user_id <", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdLessThanOrEqualTo(Integer value) {
                        addCriterion("user_id <=", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdIn(List<Integer> values) {
                        addCriterion("user_id in", values, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdNotIn(List<Integer> values) {
                        addCriterion("user_id not in", values, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdBetween(Integer value1, Integer value2) {
                        addCriterion("user_id between", value1, value2, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("user_id not between", value1, value2, "userId");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousIsNull() {
                        addCriterion("is_anonymous is null");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousIsNotNull() {
                        addCriterion("is_anonymous is not null");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousEqualTo(Boolean value) {
                        addCriterion("is_anonymous =", value, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousNotEqualTo(Boolean value) {
                        addCriterion("is_anonymous <>", value, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousGreaterThan(Boolean value) {
                        addCriterion("is_anonymous >", value, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousGreaterThanOrEqualTo(Boolean value) {
                        addCriterion("is_anonymous >=", value, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousLessThan(Boolean value) {
                        addCriterion("is_anonymous <", value, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousLessThanOrEqualTo(Boolean value) {
                        addCriterion("is_anonymous <=", value, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousIn(List<Boolean> values) {
                        addCriterion("is_anonymous in", values, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousNotIn(List<Boolean> values) {
                        addCriterion("is_anonymous not in", values, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousBetween(Boolean value1, Boolean value2) {
                        addCriterion("is_anonymous between", value1, value2, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andIsAnonymousNotBetween(Boolean value1, Boolean value2) {
                        addCriterion("is_anonymous not between", value1, value2, "isAnonymous");
                        return (Criteria) this;
                }

                public Criteria andTypeIsNull() {
                        addCriterion("type is null");
                        return (Criteria) this;
                }

                public Criteria andTypeIsNotNull() {
                        addCriterion("type is not null");
                        return (Criteria) this;
                }

                public Criteria andTypeEqualTo(Byte value) {
                        addCriterion("type =", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeNotEqualTo(Byte value) {
                        addCriterion("type <>", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeGreaterThan(Byte value) {
                        addCriterion("type >", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
                        addCriterion("type >=", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeLessThan(Byte value) {
                        addCriterion("type <", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeLessThanOrEqualTo(Byte value) {
                        addCriterion("type <=", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeIn(List<Byte> values) {
                        addCriterion("type in", values, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeNotIn(List<Byte> values) {
                        addCriterion("type not in", values, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeBetween(Byte value1, Byte value2) {
                        addCriterion("type between", value1, value2, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeNotBetween(Byte value1, Byte value2) {
                        addCriterion("type not between", value1, value2, "type");
                        return (Criteria) this;
                }

                public Criteria andSummaryIsNull() {
                        addCriterion("summary is null");
                        return (Criteria) this;
                }

                public Criteria andSummaryIsNotNull() {
                        addCriterion("summary is not null");
                        return (Criteria) this;
                }

                public Criteria andSummaryEqualTo(String value) {
                        addCriterion("summary =", value, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryNotEqualTo(String value) {
                        addCriterion("summary <>", value, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryGreaterThan(String value) {
                        addCriterion("summary >", value, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryGreaterThanOrEqualTo(String value) {
                        addCriterion("summary >=", value, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryLessThan(String value) {
                        addCriterion("summary <", value, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryLessThanOrEqualTo(String value) {
                        addCriterion("summary <=", value, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryLike(String value) {
                        addCriterion("summary like", value, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryNotLike(String value) {
                        addCriterion("summary not like", value, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryIn(List<String> values) {
                        addCriterion("summary in", values, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryNotIn(List<String> values) {
                        addCriterion("summary not in", values, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryBetween(String value1, String value2) {
                        addCriterion("summary between", value1, value2, "summary");
                        return (Criteria) this;
                }

                public Criteria andSummaryNotBetween(String value1, String value2) {
                        addCriterion("summary not between", value1, value2, "summary");
                        return (Criteria) this;
                }

                public Criteria andContentIsNull() {
                        addCriterion("content is null");
                        return (Criteria) this;
                }

                public Criteria andContentIsNotNull() {
                        addCriterion("content is not null");
                        return (Criteria) this;
                }

                public Criteria andContentEqualTo(String value) {
                        addCriterion("content =", value, "content");
                        return (Criteria) this;
                }

                public Criteria andContentNotEqualTo(String value) {
                        addCriterion("content <>", value, "content");
                        return (Criteria) this;
                }

                public Criteria andContentGreaterThan(String value) {
                        addCriterion("content >", value, "content");
                        return (Criteria) this;
                }

                public Criteria andContentGreaterThanOrEqualTo(String value) {
                        addCriterion("content >=", value, "content");
                        return (Criteria) this;
                }

                public Criteria andContentLessThan(String value) {
                        addCriterion("content <", value, "content");
                        return (Criteria) this;
                }

                public Criteria andContentLessThanOrEqualTo(String value) {
                        addCriterion("content <=", value, "content");
                        return (Criteria) this;
                }

                public Criteria andContentLike(String value) {
                        addCriterion("content like", value, "content");
                        return (Criteria) this;
                }

                public Criteria andContentNotLike(String value) {
                        addCriterion("content not like", value, "content");
                        return (Criteria) this;
                }

                public Criteria andContentIn(List<String> values) {
                        addCriterion("content in", values, "content");
                        return (Criteria) this;
                }

                public Criteria andContentNotIn(List<String> values) {
                        addCriterion("content not in", values, "content");
                        return (Criteria) this;
                }

                public Criteria andContentBetween(String value1, String value2) {
                        addCriterion("content between", value1, value2, "content");
                        return (Criteria) this;
                }

                public Criteria andContentNotBetween(String value1, String value2) {
                        addCriterion("content not between", value1, value2, "content");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlIsNull() {
                        addCriterion("picture_url is null");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlIsNotNull() {
                        addCriterion("picture_url is not null");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlEqualTo(String value) {
                        addCriterion("picture_url =", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlNotEqualTo(String value) {
                        addCriterion("picture_url <>", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlGreaterThan(String value) {
                        addCriterion("picture_url >", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlGreaterThanOrEqualTo(String value) {
                        addCriterion("picture_url >=", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlLessThan(String value) {
                        addCriterion("picture_url <", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlLessThanOrEqualTo(String value) {
                        addCriterion("picture_url <=", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlLike(String value) {
                        addCriterion("picture_url like", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlNotLike(String value) {
                        addCriterion("picture_url not like", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlIn(List<String> values) {
                        addCriterion("picture_url in", values, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlNotIn(List<String> values) {
                        addCriterion("picture_url not in", values, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlBetween(String value1, String value2) {
                        addCriterion("picture_url between", value1, value2, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlNotBetween(String value1, String value2) {
                        addCriterion("picture_url not between", value1, value2, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andGenderIsNull() {
                        addCriterion("gender is null");
                        return (Criteria) this;
                }

                public Criteria andGenderIsNotNull() {
                        addCriterion("gender is not null");
                        return (Criteria) this;
                }

                public Criteria andGenderEqualTo(Byte value) {
                        addCriterion("gender =", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderNotEqualTo(Byte value) {
                        addCriterion("gender <>", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderGreaterThan(Byte value) {
                        addCriterion("gender >", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderGreaterThanOrEqualTo(Byte value) {
                        addCriterion("gender >=", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderLessThan(Byte value) {
                        addCriterion("gender <", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderLessThanOrEqualTo(Byte value) {
                        addCriterion("gender <=", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderIn(List<Byte> values) {
                        addCriterion("gender in", values, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderNotIn(List<Byte> values) {
                        addCriterion("gender not in", values, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderBetween(Byte value1, Byte value2) {
                        addCriterion("gender between", value1, value2, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderNotBetween(Byte value1, Byte value2) {
                        addCriterion("gender not between", value1, value2, "gender");
                        return (Criteria) this;
                }

                public Criteria andBirthYearIsNull() {
                        addCriterion("birth_year is null");
                        return (Criteria) this;
                }

                public Criteria andBirthYearIsNotNull() {
                        addCriterion("birth_year is not null");
                        return (Criteria) this;
                }

                public Criteria andBirthYearEqualTo(Integer value) {
                        addCriterion("birth_year =", value, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearNotEqualTo(Integer value) {
                        addCriterion("birth_year <>", value, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearGreaterThan(Integer value) {
                        addCriterion("birth_year >", value, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearGreaterThanOrEqualTo(Integer value) {
                        addCriterion("birth_year >=", value, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearLessThan(Integer value) {
                        addCriterion("birth_year <", value, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearLessThanOrEqualTo(Integer value) {
                        addCriterion("birth_year <=", value, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearIn(List<Integer> values) {
                        addCriterion("birth_year in", values, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearNotIn(List<Integer> values) {
                        addCriterion("birth_year not in", values, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearBetween(Integer value1, Integer value2) {
                        addCriterion("birth_year between", value1, value2, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andBirthYearNotBetween(Integer value1, Integer value2) {
                        addCriterion("birth_year not between", value1, value2, "birthYear");
                        return (Criteria) this;
                }

                public Criteria andRelationIsNull() {
                        addCriterion("relation is null");
                        return (Criteria) this;
                }

                public Criteria andRelationIsNotNull() {
                        addCriterion("relation is not null");
                        return (Criteria) this;
                }

                public Criteria andRelationEqualTo(Byte value) {
                        addCriterion("relation =", value, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationNotEqualTo(Byte value) {
                        addCriterion("relation <>", value, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationGreaterThan(Byte value) {
                        addCriterion("relation >", value, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationGreaterThanOrEqualTo(Byte value) {
                        addCriterion("relation >=", value, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationLessThan(Byte value) {
                        addCriterion("relation <", value, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationLessThanOrEqualTo(Byte value) {
                        addCriterion("relation <=", value, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationIn(List<Byte> values) {
                        addCriterion("relation in", values, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationNotIn(List<Byte> values) {
                        addCriterion("relation not in", values, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationBetween(Byte value1, Byte value2) {
                        addCriterion("relation between", value1, value2, "relation");
                        return (Criteria) this;
                }

                public Criteria andRelationNotBetween(Byte value1, Byte value2) {
                        addCriterion("relation not between", value1, value2, "relation");
                        return (Criteria) this;
                }

                public Criteria andLabelsIsNull() {
                        addCriterion("labels is null");
                        return (Criteria) this;
                }

                public Criteria andLabelsIsNotNull() {
                        addCriterion("labels is not null");
                        return (Criteria) this;
                }

                public Criteria andLabelsEqualTo(String value) {
                        addCriterion("labels =", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsNotEqualTo(String value) {
                        addCriterion("labels <>", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsGreaterThan(String value) {
                        addCriterion("labels >", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsGreaterThanOrEqualTo(String value) {
                        addCriterion("labels >=", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsLessThan(String value) {
                        addCriterion("labels <", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsLessThanOrEqualTo(String value) {
                        addCriterion("labels <=", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsLike(String value) {
                        addCriterion("labels like", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsNotLike(String value) {
                        addCriterion("labels not like", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsIn(List<String> values) {
                        addCriterion("labels in", values, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsNotIn(List<String> values) {
                        addCriterion("labels not in", values, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsBetween(String value1, String value2) {
                        addCriterion("labels between", value1, value2, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsNotBetween(String value1, String value2) {
                        addCriterion("labels not between", value1, value2, "labels");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdIsNull() {
                        addCriterion("crowd_subject_id is null");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdIsNotNull() {
                        addCriterion("crowd_subject_id is not null");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdEqualTo(Integer value) {
                        addCriterion("crowd_subject_id =", value, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdNotEqualTo(Integer value) {
                        addCriterion("crowd_subject_id <>", value, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdGreaterThan(Integer value) {
                        addCriterion("crowd_subject_id >", value, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("crowd_subject_id >=", value, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdLessThan(Integer value) {
                        addCriterion("crowd_subject_id <", value, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdLessThanOrEqualTo(Integer value) {
                        addCriterion("crowd_subject_id <=", value, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdIn(List<Integer> values) {
                        addCriterion("crowd_subject_id in", values, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdNotIn(List<Integer> values) {
                        addCriterion("crowd_subject_id not in", values, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdBetween(Integer value1, Integer value2) {
                        addCriterion("crowd_subject_id between", value1, value2, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andCrowdSubjectIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("crowd_subject_id not between", value1, value2, "crowdSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdIsNull() {
                        addCriterion("region_subject_id is null");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdIsNotNull() {
                        addCriterion("region_subject_id is not null");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdEqualTo(Integer value) {
                        addCriterion("region_subject_id =", value, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdNotEqualTo(Integer value) {
                        addCriterion("region_subject_id <>", value, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdGreaterThan(Integer value) {
                        addCriterion("region_subject_id >", value, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("region_subject_id >=", value, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdLessThan(Integer value) {
                        addCriterion("region_subject_id <", value, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdLessThanOrEqualTo(Integer value) {
                        addCriterion("region_subject_id <=", value, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdIn(List<Integer> values) {
                        addCriterion("region_subject_id in", values, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdNotIn(List<Integer> values) {
                        addCriterion("region_subject_id not in", values, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdBetween(Integer value1, Integer value2) {
                        addCriterion("region_subject_id between", value1, value2, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRegionSubjectIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("region_subject_id not between", value1, value2, "regionSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdIsNull() {
                        addCriterion("other_subject_id is null");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdIsNotNull() {
                        addCriterion("other_subject_id is not null");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdEqualTo(Integer value) {
                        addCriterion("other_subject_id =", value, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdNotEqualTo(Integer value) {
                        addCriterion("other_subject_id <>", value, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdGreaterThan(Integer value) {
                        addCriterion("other_subject_id >", value, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("other_subject_id >=", value, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdLessThan(Integer value) {
                        addCriterion("other_subject_id <", value, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdLessThanOrEqualTo(Integer value) {
                        addCriterion("other_subject_id <=", value, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdIn(List<Integer> values) {
                        addCriterion("other_subject_id in", values, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdNotIn(List<Integer> values) {
                        addCriterion("other_subject_id not in", values, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdBetween(Integer value1, Integer value2) {
                        addCriterion("other_subject_id between", value1, value2, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andOtherSubjectIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("other_subject_id not between", value1, value2, "otherSubjectId");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketIsNull() {
                        addCriterion("reward_ticket is null");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketIsNotNull() {
                        addCriterion("reward_ticket is not null");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketEqualTo(Integer value) {
                        addCriterion("reward_ticket =", value, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketNotEqualTo(Integer value) {
                        addCriterion("reward_ticket <>", value, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketGreaterThan(Integer value) {
                        addCriterion("reward_ticket >", value, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketGreaterThanOrEqualTo(Integer value) {
                        addCriterion("reward_ticket >=", value, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketLessThan(Integer value) {
                        addCriterion("reward_ticket <", value, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketLessThanOrEqualTo(Integer value) {
                        addCriterion("reward_ticket <=", value, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketIn(List<Integer> values) {
                        addCriterion("reward_ticket in", values, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketNotIn(List<Integer> values) {
                        addCriterion("reward_ticket not in", values, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketBetween(Integer value1, Integer value2) {
                        addCriterion("reward_ticket between", value1, value2, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andRewardTicketNotBetween(Integer value1, Integer value2) {
                        addCriterion("reward_ticket not between", value1, value2, "rewardTicket");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountIsNull() {
                        addCriterion("answer_count is null");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountIsNotNull() {
                        addCriterion("answer_count is not null");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountEqualTo(Integer value) {
                        addCriterion("answer_count =", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountNotEqualTo(Integer value) {
                        addCriterion("answer_count <>", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountGreaterThan(Integer value) {
                        addCriterion("answer_count >", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("answer_count >=", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountLessThan(Integer value) {
                        addCriterion("answer_count <", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountLessThanOrEqualTo(Integer value) {
                        addCriterion("answer_count <=", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountIn(List<Integer> values) {
                        addCriterion("answer_count in", values, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountNotIn(List<Integer> values) {
                        addCriterion("answer_count not in", values, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountBetween(Integer value1, Integer value2) {
                        addCriterion("answer_count between", value1, value2, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("answer_count not between", value1, value2, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountIsNull() {
                        addCriterion("read_count is null");
                        return (Criteria) this;
                }

                public Criteria andReadCountIsNotNull() {
                        addCriterion("read_count is not null");
                        return (Criteria) this;
                }

                public Criteria andReadCountEqualTo(Integer value) {
                        addCriterion("read_count =", value, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountNotEqualTo(Integer value) {
                        addCriterion("read_count <>", value, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountGreaterThan(Integer value) {
                        addCriterion("read_count >", value, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("read_count >=", value, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountLessThan(Integer value) {
                        addCriterion("read_count <", value, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountLessThanOrEqualTo(Integer value) {
                        addCriterion("read_count <=", value, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountIn(List<Integer> values) {
                        addCriterion("read_count in", values, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountNotIn(List<Integer> values) {
                        addCriterion("read_count not in", values, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountBetween(Integer value1, Integer value2) {
                        addCriterion("read_count between", value1, value2, "readCount");
                        return (Criteria) this;
                }

                public Criteria andReadCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("read_count not between", value1, value2, "readCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountIsNull() {
                        addCriterion("collection_count is null");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountIsNotNull() {
                        addCriterion("collection_count is not null");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountEqualTo(Integer value) {
                        addCriterion("collection_count =", value, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountNotEqualTo(Integer value) {
                        addCriterion("collection_count <>", value, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountGreaterThan(Integer value) {
                        addCriterion("collection_count >", value, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("collection_count >=", value, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountLessThan(Integer value) {
                        addCriterion("collection_count <", value, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountLessThanOrEqualTo(Integer value) {
                        addCriterion("collection_count <=", value, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountIn(List<Integer> values) {
                        addCriterion("collection_count in", values, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountNotIn(List<Integer> values) {
                        addCriterion("collection_count not in", values, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountBetween(Integer value1, Integer value2) {
                        addCriterion("collection_count between", value1, value2, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andCollectionCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("collection_count not between", value1, value2, "collectionCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountIsNull() {
                        addCriterion("forward_count is null");
                        return (Criteria) this;
                }

                public Criteria andForwardCountIsNotNull() {
                        addCriterion("forward_count is not null");
                        return (Criteria) this;
                }

                public Criteria andForwardCountEqualTo(Integer value) {
                        addCriterion("forward_count =", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountNotEqualTo(Integer value) {
                        addCriterion("forward_count <>", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountGreaterThan(Integer value) {
                        addCriterion("forward_count >", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("forward_count >=", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountLessThan(Integer value) {
                        addCriterion("forward_count <", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountLessThanOrEqualTo(Integer value) {
                        addCriterion("forward_count <=", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountIn(List<Integer> values) {
                        addCriterion("forward_count in", values, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountNotIn(List<Integer> values) {
                        addCriterion("forward_count not in", values, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountBetween(Integer value1, Integer value2) {
                        addCriterion("forward_count between", value1, value2, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("forward_count not between", value1, value2, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdIsNull() {
                        addCriterion("best_answer_id is null");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdIsNotNull() {
                        addCriterion("best_answer_id is not null");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdEqualTo(Integer value) {
                        addCriterion("best_answer_id =", value, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdNotEqualTo(Integer value) {
                        addCriterion("best_answer_id <>", value, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdGreaterThan(Integer value) {
                        addCriterion("best_answer_id >", value, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("best_answer_id >=", value, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdLessThan(Integer value) {
                        addCriterion("best_answer_id <", value, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdLessThanOrEqualTo(Integer value) {
                        addCriterion("best_answer_id <=", value, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdIn(List<Integer> values) {
                        addCriterion("best_answer_id in", values, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdNotIn(List<Integer> values) {
                        addCriterion("best_answer_id not in", values, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdBetween(Integer value1, Integer value2) {
                        addCriterion("best_answer_id between", value1, value2, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andBestAnswerIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("best_answer_id not between", value1, value2, "bestAnswerId");
                        return (Criteria) this;
                }

                public Criteria andCityAddressIsNull() {
                        addCriterion("city_address is null");
                        return (Criteria) this;
                }

                public Criteria andCityAddressIsNotNull() {
                        addCriterion("city_address is not null");
                        return (Criteria) this;
                }

                public Criteria andCityAddressEqualTo(String value) {
                        addCriterion("city_address =", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressNotEqualTo(String value) {
                        addCriterion("city_address <>", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressGreaterThan(String value) {
                        addCriterion("city_address >", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressGreaterThanOrEqualTo(String value) {
                        addCriterion("city_address >=", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressLessThan(String value) {
                        addCriterion("city_address <", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressLessThanOrEqualTo(String value) {
                        addCriterion("city_address <=", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressLike(String value) {
                        addCriterion("city_address like", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressNotLike(String value) {
                        addCriterion("city_address not like", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressIn(List<String> values) {
                        addCriterion("city_address in", values, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressNotIn(List<String> values) {
                        addCriterion("city_address not in", values, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressBetween(String value1, String value2) {
                        addCriterion("city_address between", value1, value2, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressNotBetween(String value1, String value2) {
                        addCriterion("city_address not between", value1, value2, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeIsNull() {
                        addCriterion("last_answer_time is null");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeIsNotNull() {
                        addCriterion("last_answer_time is not null");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeEqualTo(Date value) {
                        addCriterion("last_answer_time =", value, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeNotEqualTo(Date value) {
                        addCriterion("last_answer_time <>", value, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeGreaterThan(Date value) {
                        addCriterion("last_answer_time >", value, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeGreaterThanOrEqualTo(Date value) {
                        addCriterion("last_answer_time >=", value, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeLessThan(Date value) {
                        addCriterion("last_answer_time <", value, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeLessThanOrEqualTo(Date value) {
                        addCriterion("last_answer_time <=", value, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeIn(List<Date> values) {
                        addCriterion("last_answer_time in", values, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeNotIn(List<Date> values) {
                        addCriterion("last_answer_time not in", values, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeBetween(Date value1, Date value2) {
                        addCriterion("last_answer_time between", value1, value2, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andLastAnswerTimeNotBetween(Date value1, Date value2) {
                        addCriterion("last_answer_time not between", value1, value2, "lastAnswerTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIsNull() {
                        addCriterion("create_time is null");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIsNotNull() {
                        addCriterion("create_time is not null");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeEqualTo(Date value) {
                        addCriterion("create_time =", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotEqualTo(Date value) {
                        addCriterion("create_time <>", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeGreaterThan(Date value) {
                        addCriterion("create_time >", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
                        addCriterion("create_time >=", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeLessThan(Date value) {
                        addCriterion("create_time <", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
                        addCriterion("create_time <=", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIn(List<Date> values) {
                        addCriterion("create_time in", values, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotIn(List<Date> values) {
                        addCriterion("create_time not in", values, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeBetween(Date value1, Date value2) {
                        addCriterion("create_time between", value1, value2, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
                        addCriterion("create_time not between", value1, value2, "createTime");
                        return (Criteria) this;
                }
        }

        /**
         * This class was generated by MyBatis Generator. This class corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public static class Criterion {
                private String condition;
                private Object value;
                private Object secondValue;
                private boolean noValue;
                private boolean singleValue;
                private boolean betweenValue;
                private boolean listValue;
                private String typeHandler;

                public String getCondition() {
                        return condition;
                }

                public Object getValue() {
                        return value;
                }

                public Object getSecondValue() {
                        return secondValue;
                }

                public boolean isNoValue() {
                        return noValue;
                }

                public boolean isSingleValue() {
                        return singleValue;
                }

                public boolean isBetweenValue() {
                        return betweenValue;
                }

                public boolean isListValue() {
                        return listValue;
                }

                public String getTypeHandler() {
                        return typeHandler;
                }

                protected Criterion(String condition) {
                        super();
                        this.condition = condition;
                        this.typeHandler = null;
                        this.noValue = true;
                }

                protected Criterion(String condition, Object value, String typeHandler) {
                        super();
                        this.condition = condition;
                        this.value = value;
                        this.typeHandler = typeHandler;
                        if (value instanceof List<?>) {
                                this.listValue = true;
                        } else {
                                this.singleValue = true;
                        }
                }

                protected Criterion(String condition, Object value) {
                        this(condition, value, null);
                }

                protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
                        super();
                        this.condition = condition;
                        this.value = value;
                        this.secondValue = secondValue;
                        this.typeHandler = typeHandler;
                        this.betweenValue = true;
                }

                protected Criterion(String condition, Object value, Object secondValue) {
                        this(condition, value, secondValue, null);
                }
        }

/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 26 19:54:29 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}