package com.ayue.sp.db.po;

import java.util.Date;

public class Question {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.is_anonymous
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Boolean isAnonymous;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.type
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Byte type;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.summary
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String summary;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String content;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.picture_url
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String pictureUrl;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.gender
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Byte gender;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.birth_year
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer birthYear;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.relation
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Byte relation;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.labels
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String labels;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.crowd_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer crowdSubjectId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.region_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer regionSubjectId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.other_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer otherSubjectId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.reward_ticket
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer rewardTicket;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.answer_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer answerCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.read_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer readCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.collection_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer collectionCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.forward_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer forwardCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.best_answer_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer bestAnswerId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.city_address
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String cityAddress;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.last_answer_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date lastAnswerTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer status;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.id
         * @return  the value of answer.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getStatus() {
                return status;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.user_id
         * @param status  the value for answer.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setStatus(Integer status) {
                this.status = status;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.id
         * @return  the value of question.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.id
         * @param id  the value for question.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.user_id
         * @return  the value of question.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.user_id
         * @param userId  the value for question.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.is_anonymous
         * @return  the value of question.is_anonymous
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Boolean getIsAnonymous() {
                return isAnonymous;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.is_anonymous
         * @param isAnonymous  the value for question.is_anonymous
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setIsAnonymous(Boolean isAnonymous) {
                this.isAnonymous = isAnonymous;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.type
         * @return  the value of question.type
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Byte getType() {
                return type;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.type
         * @param type  the value for question.type
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setType(Byte type) {
                this.type = type;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.summary
         * @return  the value of question.summary
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getSummary() {
                return summary;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.summary
         * @param summary  the value for question.summary
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setSummary(String summary) {
                this.summary = summary;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.content
         * @return  the value of question.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getContent() {
                return content;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.content
         * @param content  the value for question.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setContent(String content) {
                this.content = content;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.picture_url
         * @return  the value of question.picture_url
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getPictureUrl() {
                return pictureUrl;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.picture_url
         * @param pictureUrl  the value for question.picture_url
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setPictureUrl(String pictureUrl) {
                this.pictureUrl = pictureUrl;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.gender
         * @return  the value of question.gender
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Byte getGender() {
                return gender;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.gender
         * @param gender  the value for question.gender
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setGender(Byte gender) {
                this.gender = gender;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.birth_year
         * @return  the value of question.birth_year
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getBirthYear() {
                return birthYear;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.birth_year
         * @param birthYear  the value for question.birth_year
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setBirthYear(Integer birthYear) {
                this.birthYear = birthYear;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.relation
         * @return  the value of question.relation
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Byte getRelation() {
                return relation;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.relation
         * @param relation  the value for question.relation
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setRelation(Byte relation) {
                this.relation = relation;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.labels
         * @return  the value of question.labels
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getLabels() {
                return labels;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.labels
         * @param labels  the value for question.labels
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setLabels(String labels) {
                this.labels = labels;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.crowd_subject_id
         * @return  the value of question.crowd_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getCrowdSubjectId() {
                return crowdSubjectId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.crowd_subject_id
         * @param crowdSubjectId  the value for question.crowd_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCrowdSubjectId(Integer crowdSubjectId) {
                this.crowdSubjectId = crowdSubjectId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.region_subject_id
         * @return  the value of question.region_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getRegionSubjectId() {
                return regionSubjectId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.region_subject_id
         * @param regionSubjectId  the value for question.region_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setRegionSubjectId(Integer regionSubjectId) {
                this.regionSubjectId = regionSubjectId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.other_subject_id
         * @return  the value of question.other_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getOtherSubjectId() {
                return otherSubjectId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.other_subject_id
         * @param otherSubjectId  the value for question.other_subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setOtherSubjectId(Integer otherSubjectId) {
                this.otherSubjectId = otherSubjectId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.reward_ticket
         * @return  the value of question.reward_ticket
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getRewardTicket() {
                return rewardTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.reward_ticket
         * @param rewardTicket  the value for question.reward_ticket
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setRewardTicket(Integer rewardTicket) {
                this.rewardTicket = rewardTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.answer_count
         * @return  the value of question.answer_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getAnswerCount() {
                return answerCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.answer_count
         * @param answerCount  the value for question.answer_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setAnswerCount(Integer answerCount) {
                this.answerCount = answerCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.read_count
         * @return  the value of question.read_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getReadCount() {
                return readCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.read_count
         * @param readCount  the value for question.read_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setReadCount(Integer readCount) {
                this.readCount = readCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.collection_count
         * @return  the value of question.collection_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getCollectionCount() {
                return collectionCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.collection_count
         * @param collectionCount  the value for question.collection_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCollectionCount(Integer collectionCount) {
                this.collectionCount = collectionCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.forward_count
         * @return  the value of question.forward_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getForwardCount() {
                return forwardCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.forward_count
         * @param forwardCount  the value for question.forward_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setForwardCount(Integer forwardCount) {
                this.forwardCount = forwardCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.best_answer_id
         * @return  the value of question.best_answer_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getBestAnswerId() {
                return bestAnswerId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.best_answer_id
         * @param bestAnswerId  the value for question.best_answer_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setBestAnswerId(Integer bestAnswerId) {
                this.bestAnswerId = bestAnswerId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.city_address
         * @return  the value of question.city_address
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getCityAddress() {
                return cityAddress;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.city_address
         * @param cityAddress  the value for question.city_address
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCityAddress(String cityAddress) {
                this.cityAddress = cityAddress;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.last_answer_time
         * @return  the value of question.last_answer_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getLastAnswerTime() {
                return lastAnswerTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.last_answer_time
         * @param lastAnswerTime  the value for question.last_answer_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setLastAnswerTime(Date lastAnswerTime) {
                this.lastAnswerTime = lastAnswerTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question.create_time
         * @return  the value of question.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question.create_time
         * @param createTime  the value for question.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}