package com.ayue.sp.db.po;

import java.util.Date;

public class QuestionLinkRecord {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question_link_record.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question_link_record.father_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer fatherId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column question_link_record.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question_link_record.id
         * @return  the value of question_link_record.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question_link_record.id
         * @param id  the value for question_link_record.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question_link_record.father_id
         * @return  the value of question_link_record.father_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getFatherId() {
                return fatherId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question_link_record.father_id
         * @param fatherId  the value for question_link_record.father_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setFatherId(Integer fatherId) {
                this.fatherId = fatherId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column question_link_record.create_time
         * @return  the value of question_link_record.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column question_link_record.create_time
         * @param createTime  the value for question_link_record.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}