package com.ayue.sp.db.po;

import java.util.Date;

public class Reply {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column reply.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column reply.comment_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer commentId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column reply.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column reply.target_user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer targetUserId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column reply.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String content;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column reply.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer agreeCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column reply.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column answer.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer status;
        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column answer.id
         * @return  the value of answer.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getStatus() {
                return status;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column answer.user_id
         * @param status  the value for answer.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setStatus(Integer status) {
                this.status = status;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column reply.id
         * @return  the value of reply.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column reply.id
         * @param id  the value for reply.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column reply.comment_id
         * @return  the value of reply.comment_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getCommentId() {
                return commentId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column reply.comment_id
         * @param commentId  the value for reply.comment_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCommentId(Integer commentId) {
                this.commentId = commentId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column reply.user_id
         * @return  the value of reply.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column reply.user_id
         * @param userId  the value for reply.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column reply.target_user_id
         * @return  the value of reply.target_user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getTargetUserId() {
                return targetUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column reply.target_user_id
         * @param targetUserId  the value for reply.target_user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setTargetUserId(Integer targetUserId) {
                this.targetUserId = targetUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column reply.content
         * @return  the value of reply.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getContent() {
                return content;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column reply.content
         * @param content  the value for reply.content
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setContent(String content) {
                this.content = content;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column reply.agree_count
         * @return  the value of reply.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getAgreeCount() {
                return agreeCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column reply.agree_count
         * @param agreeCount  the value for reply.agree_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setAgreeCount(Integer agreeCount) {
                this.agreeCount = agreeCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column reply.create_time
         * @return  the value of reply.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column reply.create_time
         * @param createTime  the value for reply.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}