package com.ayue.sp.db.po;

import java.util.Date;

public class Subject {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.id
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.type
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private Byte type;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.name
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private String name;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.avatar
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private String avatar;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.description
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private String description;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.is_system
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private Boolean isSystem;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.admini_user_id
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private Integer adminiUserId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.member_count
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private Integer memberCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.create_time
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column subject.status
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        private Byte status;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.id
         * @return  the value of subject.id
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.id
         * @param id  the value for subject.id
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.type
         * @return  the value of subject.type
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public Byte getType() {
                return type;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.type
         * @param type  the value for subject.type
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setType(Byte type) {
                this.type = type;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.name
         * @return  the value of subject.name
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public String getName() {
                return name;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.name
         * @param name  the value for subject.name
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setName(String name) {
                this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.avatar
         * @return  the value of subject.avatar
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public String getAvatar() {
                return avatar;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.avatar
         * @param avatar  the value for subject.avatar
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setAvatar(String avatar) {
                this.avatar = avatar;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.description
         * @return  the value of subject.description
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public String getDescription() {
                return description;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.description
         * @param description  the value for subject.description
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setDescription(String description) {
                this.description = description;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.is_system
         * @return  the value of subject.is_system
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public Boolean getIsSystem() {
                return isSystem;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.is_system
         * @param isSystem  the value for subject.is_system
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setIsSystem(Boolean isSystem) {
                this.isSystem = isSystem;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.admini_user_id
         * @return  the value of subject.admini_user_id
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public Integer getAdminiUserId() {
                return adminiUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.admini_user_id
         * @param adminiUserId  the value for subject.admini_user_id
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setAdminiUserId(Integer adminiUserId) {
                this.adminiUserId = adminiUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.member_count
         * @return  the value of subject.member_count
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public Integer getMemberCount() {
                return memberCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.member_count
         * @param memberCount  the value for subject.member_count
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setMemberCount(Integer memberCount) {
                this.memberCount = memberCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.create_time
         * @return  the value of subject.create_time
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.create_time
         * @param createTime  the value for subject.create_time
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column subject.status
         * @return  the value of subject.status
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public Byte getStatus() {
                return status;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column subject.status
         * @param status  the value for subject.status
         * @mbg.generated  Thu Oct 08 11:50:26 CST 2020
         */
        public void setStatus(Byte status) {
                this.status = status;
        }
}