package com.ayue.sp.db.po;

import java.util.Date;

public class UserAttention {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_attention.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_attention.attention_user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer attentionUserId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_attention.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_attention.user_id
         * @return  the value of user_attention.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_attention.user_id
         * @param userId  the value for user_attention.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_attention.attention_user_id
         * @return  the value of user_attention.attention_user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getAttentionUserId() {
                return attentionUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_attention.attention_user_id
         * @param attentionUserId  the value for user_attention.attention_user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setAttentionUserId(Integer attentionUserId) {
                this.attentionUserId = attentionUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_attention.create_time
         * @return  the value of user_attention.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_attention.create_time
         * @param createTime  the value for user_attention.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}