package com.ayue.sp.db.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserTipoffsExample {
    /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        protected String orderByClause;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        protected boolean distinct;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        protected List<Criteria> oredCriteria;

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public UserTipoffsExample() {
                oredCriteria = new ArrayList<Criteria>();
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setOrderByClause(String orderByClause) {
                this.orderByClause = orderByClause;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public String getOrderByClause() {
                return orderByClause;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setDistinct(boolean distinct) {
                this.distinct = distinct;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public boolean isDistinct() {
                return distinct;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public List<Criteria> getOredCriteria() {
                return oredCriteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void or(Criteria criteria) {
                oredCriteria.add(criteria);
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public Criteria or() {
                Criteria criteria = createCriteriaInternal();
                oredCriteria.add(criteria);
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public Criteria createCriteria() {
                Criteria criteria = createCriteriaInternal();
                if (oredCriteria.size() == 0) {
                        oredCriteria.add(criteria);
                }
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        protected Criteria createCriteriaInternal() {
                Criteria criteria = new Criteria();
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void clear() {
                oredCriteria.clear();
                orderByClause = null;
                distinct = false;
        }

        /**
         * This class was generated by MyBatis Generator. This class corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        protected abstract static class GeneratedCriteria {
                protected List<Criterion> criteria;

                protected GeneratedCriteria() {
                        super();
                        criteria = new ArrayList<Criterion>();
                }

                public boolean isValid() {
                        return criteria.size() > 0;
                }

                public List<Criterion> getAllCriteria() {
                        return criteria;
                }

                public List<Criterion> getCriteria() {
                        return criteria;
                }

                protected void addCriterion(String condition) {
                        if (condition == null) {
                                throw new RuntimeException("Value for condition cannot be null");
                        }
                        criteria.add(new Criterion(condition));
                }

                protected void addCriterion(String condition, Object value, String property) {
                        if (value == null) {
                                throw new RuntimeException("Value for " + property + " cannot be null");
                        }
                        criteria.add(new Criterion(condition, value));
                }

                protected void addCriterion(String condition, Object value1, Object value2, String property) {
                        if (value1 == null || value2 == null) {
                                throw new RuntimeException("Between values for " + property + " cannot be null");
                        }
                        criteria.add(new Criterion(condition, value1, value2));
                }

                public Criteria andTargetUserIdIsNull() {
                        addCriterion("target_user_id is null");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdIsNotNull() {
                        addCriterion("target_user_id is not null");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdEqualTo(Integer value) {
                        addCriterion("target_user_id =", value, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdNotEqualTo(Integer value) {
                        addCriterion("target_user_id <>", value, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdGreaterThan(Integer value) {
                        addCriterion("target_user_id >", value, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("target_user_id >=", value, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdLessThan(Integer value) {
                        addCriterion("target_user_id <", value, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdLessThanOrEqualTo(Integer value) {
                        addCriterion("target_user_id <=", value, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdIn(List<Integer> values) {
                        addCriterion("target_user_id in", values, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdNotIn(List<Integer> values) {
                        addCriterion("target_user_id not in", values, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdBetween(Integer value1, Integer value2) {
                        addCriterion("target_user_id between", value1, value2, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andTargetUserIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("target_user_id not between", value1, value2, "targetUserId");
                        return (Criteria) this;
                }

                public Criteria andUserIdIsNull() {
                        addCriterion("user_id is null");
                        return (Criteria) this;
                }

                public Criteria andUserIdIsNotNull() {
                        addCriterion("user_id is not null");
                        return (Criteria) this;
                }

                public Criteria andUserIdEqualTo(Integer value) {
                        addCriterion("user_id =", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdNotEqualTo(Integer value) {
                        addCriterion("user_id <>", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdGreaterThan(Integer value) {
                        addCriterion("user_id >", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("user_id >=", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdLessThan(Integer value) {
                        addCriterion("user_id <", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdLessThanOrEqualTo(Integer value) {
                        addCriterion("user_id <=", value, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdIn(List<Integer> values) {
                        addCriterion("user_id in", values, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdNotIn(List<Integer> values) {
                        addCriterion("user_id not in", values, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdBetween(Integer value1, Integer value2) {
                        addCriterion("user_id between", value1, value2, "userId");
                        return (Criteria) this;
                }

                public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("user_id not between", value1, value2, "userId");
                        return (Criteria) this;
                }

                public Criteria andTypeIsNull() {
                        addCriterion("type is null");
                        return (Criteria) this;
                }

                public Criteria andTypeIsNotNull() {
                        addCriterion("type is not null");
                        return (Criteria) this;
                }

                public Criteria andTypeEqualTo(Byte value) {
                        addCriterion("type =", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeNotEqualTo(Byte value) {
                        addCriterion("type <>", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeGreaterThan(Byte value) {
                        addCriterion("type >", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
                        addCriterion("type >=", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeLessThan(Byte value) {
                        addCriterion("type <", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeLessThanOrEqualTo(Byte value) {
                        addCriterion("type <=", value, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeIn(List<Byte> values) {
                        addCriterion("type in", values, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeNotIn(List<Byte> values) {
                        addCriterion("type not in", values, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeBetween(Byte value1, Byte value2) {
                        addCriterion("type between", value1, value2, "type");
                        return (Criteria) this;
                }

                public Criteria andTypeNotBetween(Byte value1, Byte value2) {
                        addCriterion("type not between", value1, value2, "type");
                        return (Criteria) this;
                }

                public Criteria andDescriptionIsNull() {
                        addCriterion("description is null");
                        return (Criteria) this;
                }

                public Criteria andDescriptionIsNotNull() {
                        addCriterion("description is not null");
                        return (Criteria) this;
                }

                public Criteria andDescriptionEqualTo(String value) {
                        addCriterion("description =", value, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionNotEqualTo(String value) {
                        addCriterion("description <>", value, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionGreaterThan(String value) {
                        addCriterion("description >", value, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
                        addCriterion("description >=", value, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionLessThan(String value) {
                        addCriterion("description <", value, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionLessThanOrEqualTo(String value) {
                        addCriterion("description <=", value, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionLike(String value) {
                        addCriterion("description like", value, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionNotLike(String value) {
                        addCriterion("description not like", value, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionIn(List<String> values) {
                        addCriterion("description in", values, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionNotIn(List<String> values) {
                        addCriterion("description not in", values, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionBetween(String value1, String value2) {
                        addCriterion("description between", value1, value2, "description");
                        return (Criteria) this;
                }

                public Criteria andDescriptionNotBetween(String value1, String value2) {
                        addCriterion("description not between", value1, value2, "description");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlIsNull() {
                        addCriterion("picture_url is null");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlIsNotNull() {
                        addCriterion("picture_url is not null");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlEqualTo(String value) {
                        addCriterion("picture_url =", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlNotEqualTo(String value) {
                        addCriterion("picture_url <>", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlGreaterThan(String value) {
                        addCriterion("picture_url >", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlGreaterThanOrEqualTo(String value) {
                        addCriterion("picture_url >=", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlLessThan(String value) {
                        addCriterion("picture_url <", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlLessThanOrEqualTo(String value) {
                        addCriterion("picture_url <=", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlLike(String value) {
                        addCriterion("picture_url like", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlNotLike(String value) {
                        addCriterion("picture_url not like", value, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlIn(List<String> values) {
                        addCriterion("picture_url in", values, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlNotIn(List<String> values) {
                        addCriterion("picture_url not in", values, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlBetween(String value1, String value2) {
                        addCriterion("picture_url between", value1, value2, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andPictureUrlNotBetween(String value1, String value2) {
                        addCriterion("picture_url not between", value1, value2, "pictureUrl");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIsNull() {
                        addCriterion("create_time is null");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIsNotNull() {
                        addCriterion("create_time is not null");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeEqualTo(Date value) {
                        addCriterion("create_time =", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotEqualTo(Date value) {
                        addCriterion("create_time <>", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeGreaterThan(Date value) {
                        addCriterion("create_time >", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
                        addCriterion("create_time >=", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeLessThan(Date value) {
                        addCriterion("create_time <", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
                        addCriterion("create_time <=", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIn(List<Date> values) {
                        addCriterion("create_time in", values, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotIn(List<Date> values) {
                        addCriterion("create_time not in", values, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeBetween(Date value1, Date value2) {
                        addCriterion("create_time between", value1, value2, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
                        addCriterion("create_time not between", value1, value2, "createTime");
                        return (Criteria) this;
                }

                public Criteria andIsDealedIsNull() {
                        addCriterion("is_dealed is null");
                        return (Criteria) this;
                }

                public Criteria andIsDealedIsNotNull() {
                        addCriterion("is_dealed is not null");
                        return (Criteria) this;
                }

                public Criteria andIsDealedEqualTo(Boolean value) {
                        addCriterion("is_dealed =", value, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedNotEqualTo(Boolean value) {
                        addCriterion("is_dealed <>", value, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedGreaterThan(Boolean value) {
                        addCriterion("is_dealed >", value, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedGreaterThanOrEqualTo(Boolean value) {
                        addCriterion("is_dealed >=", value, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedLessThan(Boolean value) {
                        addCriterion("is_dealed <", value, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedLessThanOrEqualTo(Boolean value) {
                        addCriterion("is_dealed <=", value, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedIn(List<Boolean> values) {
                        addCriterion("is_dealed in", values, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedNotIn(List<Boolean> values) {
                        addCriterion("is_dealed not in", values, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedBetween(Boolean value1, Boolean value2) {
                        addCriterion("is_dealed between", value1, value2, "isDealed");
                        return (Criteria) this;
                }

                public Criteria andIsDealedNotBetween(Boolean value1, Boolean value2) {
                        addCriterion("is_dealed not between", value1, value2, "isDealed");
                        return (Criteria) this;
                }
        }

        /**
         * This class was generated by MyBatis Generator. This class corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public static class Criterion {
                private String condition;
                private Object value;
                private Object secondValue;
                private boolean noValue;
                private boolean singleValue;
                private boolean betweenValue;
                private boolean listValue;
                private String typeHandler;

                public String getCondition() {
                        return condition;
                }

                public Object getValue() {
                        return value;
                }

                public Object getSecondValue() {
                        return secondValue;
                }

                public boolean isNoValue() {
                        return noValue;
                }

                public boolean isSingleValue() {
                        return singleValue;
                }

                public boolean isBetweenValue() {
                        return betweenValue;
                }

                public boolean isListValue() {
                        return listValue;
                }

                public String getTypeHandler() {
                        return typeHandler;
                }

                protected Criterion(String condition) {
                        super();
                        this.condition = condition;
                        this.typeHandler = null;
                        this.noValue = true;
                }

                protected Criterion(String condition, Object value, String typeHandler) {
                        super();
                        this.condition = condition;
                        this.value = value;
                        this.typeHandler = typeHandler;
                        if (value instanceof List<?>) {
                                this.listValue = true;
                        } else {
                                this.singleValue = true;
                        }
                }

                protected Criterion(String condition, Object value) {
                        this(condition, value, null);
                }

                protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
                        super();
                        this.condition = condition;
                        this.value = value;
                        this.secondValue = secondValue;
                        this.typeHandler = typeHandler;
                        this.betweenValue = true;
                }

                protected Criterion(String condition, Object value, Object secondValue) {
                        this(condition, value, secondValue, null);
                }
        }

/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_tipoffs
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 07 15:00:21 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}