package com.ayue.sp.db.po;

import java.util.Date;

public class UserRecharge {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_recharge.out_trade_no
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private String outTradeNo;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_recharge.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_recharge.money_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer moneyCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_recharge.status
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Byte status;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_recharge.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_recharge.update_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date updateTime;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_recharge.out_trade_no
         * @return  the value of user_recharge.out_trade_no
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public String getOutTradeNo() {
                return outTradeNo;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_recharge.out_trade_no
         * @param outTradeNo  the value for user_recharge.out_trade_no
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setOutTradeNo(String outTradeNo) {
                this.outTradeNo = outTradeNo;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_recharge.user_id
         * @return  the value of user_recharge.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_recharge.user_id
         * @param userId  the value for user_recharge.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_recharge.money_count
         * @return  the value of user_recharge.money_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getMoneyCount() {
                return moneyCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_recharge.money_count
         * @param moneyCount  the value for user_recharge.money_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setMoneyCount(Integer moneyCount) {
                this.moneyCount = moneyCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_recharge.status
         * @return  the value of user_recharge.status
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Byte getStatus() {
                return status;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_recharge.status
         * @param status  the value for user_recharge.status
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setStatus(Byte status) {
                this.status = status;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_recharge.create_time
         * @return  the value of user_recharge.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_recharge.create_time
         * @param createTime  the value for user_recharge.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_recharge.update_time
         * @return  the value of user_recharge.update_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getUpdateTime() {
                return updateTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_recharge.update_time
         * @param updateTime  the value for user_recharge.update_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUpdateTime(Date updateTime) {
                this.updateTime = updateTime;
        }
}