package com.ayue.sp.db.po;

import java.util.Date;

public class UserBrowse {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_browse.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_browse.question_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer questionId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_browse.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_browse.user_id
         * @return  the value of user_browse.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_browse.user_id
         * @param userId  the value for user_browse.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_browse.question_id
         * @return  the value of user_browse.question_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getQuestionId() {
                return questionId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_browse.question_id
         * @param questionId  the value for user_browse.question_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setQuestionId(Integer questionId) {
                this.questionId = questionId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_browse.create_time
         * @return  the value of user_browse.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_browse.create_time
         * @param createTime  the value for user_browse.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}