package com.ayue.sp.db.po;

import java.util.Date;

public class UserConvert {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_convert.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_convert.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_convert.ticket_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer ticketCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_convert.is_success
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Boolean isSuccess;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_convert.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_convert.id
         * @return  the value of user_convert.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_convert.id
         * @param id  the value for user_convert.id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_convert.user_id
         * @return  the value of user_convert.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_convert.user_id
         * @param userId  the value for user_convert.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_convert.ticket_count
         * @return  the value of user_convert.ticket_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getTicketCount() {
                return ticketCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_convert.ticket_count
         * @param ticketCount  the value for user_convert.ticket_count
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setTicketCount(Integer ticketCount) {
                this.ticketCount = ticketCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_convert.is_success
         * @return  the value of user_convert.is_success
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Boolean getIsSuccess() {
                return isSuccess;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_convert.is_success
         * @param isSuccess  the value for user_convert.is_success
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setIsSuccess(Boolean isSuccess) {
                this.isSuccess = isSuccess;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_convert.create_time
         * @return  the value of user_convert.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_convert.create_time
         * @param createTime  the value for user_convert.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}