package com.ayue.sp.db.po;

import java.util.Date;

public class UserNews {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_news.id
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_news.user_id
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_news.type
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        private Byte type;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_news.title
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        private String title;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_news.content
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        private String content;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_news.param
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        private String param;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_news.is_read
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        private Boolean isRead;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_news.create_time
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        private Date createTime;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_news.id
         * @return  the value of user_news.id
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_news.id
         * @param id  the value for user_news.id
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_news.user_id
         * @return  the value of user_news.user_id
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_news.user_id
         * @param userId  the value for user_news.user_id
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_news.type
         * @return  the value of user_news.type
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public Byte getType() {
                return type;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_news.type
         * @param type  the value for user_news.type
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public void setType(Byte type) {
                this.type = type;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_news.title
         * @return  the value of user_news.title
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public String getTitle() {
                return title;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_news.title
         * @param title  the value for user_news.title
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public void setTitle(String title) {
                this.title = title;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_news.content
         * @return  the value of user_news.content
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public String getContent() {
                return content;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_news.content
         * @param content  the value for user_news.content
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public void setContent(String content) {
                this.content = content;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_news.param
         * @return  the value of user_news.param
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public String getParam() {
                return param;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_news.param
         * @param param  the value for user_news.param
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public void setParam(String param) {
                this.param = param;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_news.is_read
         * @return  the value of user_news.is_read
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public Boolean getIsRead() {
                return isRead;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_news.is_read
         * @param isRead  the value for user_news.is_read
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public void setIsRead(Boolean isRead) {
                this.isRead = isRead;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_news.create_time
         * @return  the value of user_news.create_time
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_news.create_time
         * @param createTime  the value for user_news.create_time
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}