package com.ayue.sp.db.po;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class UserExample {
    /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        protected String orderByClause;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        protected boolean distinct;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        protected List<Criteria> oredCriteria;

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public UserExample() {
                oredCriteria = new ArrayList<Criteria>();
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setOrderByClause(String orderByClause) {
                this.orderByClause = orderByClause;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getOrderByClause() {
                return orderByClause;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setDistinct(boolean distinct) {
                this.distinct = distinct;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public boolean isDistinct() {
                return distinct;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public List<Criteria> getOredCriteria() {
                return oredCriteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void or(Criteria criteria) {
                oredCriteria.add(criteria);
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Criteria or() {
                Criteria criteria = createCriteriaInternal();
                oredCriteria.add(criteria);
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Criteria createCriteria() {
                Criteria criteria = createCriteriaInternal();
                if (oredCriteria.size() == 0) {
                        oredCriteria.add(criteria);
                }
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        protected Criteria createCriteriaInternal() {
                Criteria criteria = new Criteria();
                return criteria;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void clear() {
                oredCriteria.clear();
                orderByClause = null;
                distinct = false;
        }

        /**
         * This class was generated by MyBatis Generator. This class corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        protected abstract static class GeneratedCriteria {
                protected List<Criterion> criteria;

                protected GeneratedCriteria() {
                        super();
                        criteria = new ArrayList<Criterion>();
                }

                public boolean isValid() {
                        return criteria.size() > 0;
                }

                public List<Criterion> getAllCriteria() {
                        return criteria;
                }

                public List<Criterion> getCriteria() {
                        return criteria;
                }

                protected void addCriterion(String condition) {
                        if (condition == null) {
                                throw new RuntimeException("Value for condition cannot be null");
                        }
                        criteria.add(new Criterion(condition));
                }

                protected void addCriterion(String condition, Object value, String property) {
                        if (value == null) {
                                throw new RuntimeException("Value for " + property + " cannot be null");
                        }
                        criteria.add(new Criterion(condition, value));
                }

                protected void addCriterion(String condition, Object value1, Object value2, String property) {
                        if (value1 == null || value2 == null) {
                                throw new RuntimeException("Between values for " + property + " cannot be null");
                        }
                        criteria.add(new Criterion(condition, value1, value2));
                }

                public Criteria andIdIsNull() {
                        addCriterion("id is null");
                        return (Criteria) this;
                }

                public Criteria andIdIsNotNull() {
                        addCriterion("id is not null");
                        return (Criteria) this;
                }

                public Criteria andIdentityTo(Integer value) {
                        addCriterion("identity =", value, "identity");
                        return (Criteria) this;
                }
                public Criteria andIdEqualTo(Integer value) {
                        addCriterion("id =", value, "id");
                        return (Criteria) this;
                }
                public Criteria andTeacherEqualTo(Integer value) {
                        addCriterion("teacher =", value, "teacher");
                        return (Criteria) this;
                }

                public Criteria andIdNotEqualTo(Integer value) {
                        addCriterion("id <>", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdGreaterThan(Integer value) {
                        addCriterion("id >", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdGreaterThanOrEqualTo(Integer value) {
                        addCriterion("id >=", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdLessThan(Integer value) {
                        addCriterion("id <", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdLessThanOrEqualTo(Integer value) {
                        addCriterion("id <=", value, "id");
                        return (Criteria) this;
                }

                public Criteria andIdIn(List<Integer> values) {
                        addCriterion("id in", values, "id");
                        return (Criteria) this;
                }

                public Criteria andIdNotIn(List<Integer> values) {
                        addCriterion("id not in", values, "id");
                        return (Criteria) this;
                }

                public Criteria andIdBetween(Integer value1, Integer value2) {
                        addCriterion("id between", value1, value2, "id");
                        return (Criteria) this;
                }

                public Criteria andIdNotBetween(Integer value1, Integer value2) {
                        addCriterion("id not between", value1, value2, "id");
                        return (Criteria) this;
                }

                public Criteria andOpenidIsNull() {
                        addCriterion("openId is null");
                        return (Criteria) this;
                }

                public Criteria andOpenidIsNotNull() {
                        addCriterion("openId is not null");
                        return (Criteria) this;
                }

                public Criteria andOpenidEqualTo(String value) {
                        addCriterion("openId =", value, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidNotEqualTo(String value) {
                        addCriterion("openId <>", value, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidGreaterThan(String value) {
                        addCriterion("openId >", value, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidGreaterThanOrEqualTo(String value) {
                        addCriterion("openId >=", value, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidLessThan(String value) {
                        addCriterion("openId <", value, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidLessThanOrEqualTo(String value) {
                        addCriterion("openId <=", value, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidLike(String value) {
                        addCriterion("openId like", value, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidNotLike(String value) {
                        addCriterion("openId not like", value, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidIn(List<String> values) {
                        addCriterion("openId in", values, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidNotIn(List<String> values) {
                        addCriterion("openId not in", values, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidBetween(String value1, String value2) {
                        addCriterion("openId between", value1, value2, "openid");
                        return (Criteria) this;
                }

                public Criteria andOpenidNotBetween(String value1, String value2) {
                        addCriterion("openId not between", value1, value2, "openid");
                        return (Criteria) this;
                }

                public Criteria andGenderIsNull() {
                        addCriterion("gender is null");
                        return (Criteria) this;
                }

                public Criteria andGenderIsNotNull() {
                        addCriterion("gender is not null");
                        return (Criteria) this;
                }

                public Criteria andGenderEqualTo(Byte value) {
                        addCriterion("gender =", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderNotEqualTo(Byte value) {
                        addCriterion("gender <>", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderGreaterThan(Byte value) {
                        addCriterion("gender >", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderGreaterThanOrEqualTo(Byte value) {
                        addCriterion("gender >=", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderLessThan(Byte value) {
                        addCriterion("gender <", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderLessThanOrEqualTo(Byte value) {
                        addCriterion("gender <=", value, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderIn(List<Byte> values) {
                        addCriterion("gender in", values, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderNotIn(List<Byte> values) {
                        addCriterion("gender not in", values, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderBetween(Byte value1, Byte value2) {
                        addCriterion("gender between", value1, value2, "gender");
                        return (Criteria) this;
                }

                public Criteria andGenderNotBetween(Byte value1, Byte value2) {
                        addCriterion("gender not between", value1, value2, "gender");
                        return (Criteria) this;
                }

                public Criteria andNameIsNull() {
                        addCriterion("name is null");
                        return (Criteria) this;
                }

                public Criteria andNameIsNotNull() {
                        addCriterion("name is not null");
                        return (Criteria) this;
                }

                public Criteria andNameEqualTo(String value) {
                        addCriterion("name =", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameNotEqualTo(String value) {
                        addCriterion("name <>", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameGreaterThan(String value) {
                        addCriterion("name >", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameGreaterThanOrEqualTo(String value) {
                        addCriterion("name >=", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameLessThan(String value) {
                        addCriterion("name <", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameLessThanOrEqualTo(String value) {
                        addCriterion("name <=", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameLike(String value) {
                        addCriterion("name like", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameNotLike(String value) {
                        addCriterion("name not like", value, "name");
                        return (Criteria) this;
                }

                public Criteria andNameIn(List<String> values) {
                        addCriterion("name in", values, "name");
                        return (Criteria) this;
                }

                public Criteria andNameNotIn(List<String> values) {
                        addCriterion("name not in", values, "name");
                        return (Criteria) this;
                }

                public Criteria andNameBetween(String value1, String value2) {
                        addCriterion("name between", value1, value2, "name");
                        return (Criteria) this;
                }

                public Criteria andNameNotBetween(String value1, String value2) {
                        addCriterion("name not between", value1, value2, "name");
                        return (Criteria) this;
                }

                public Criteria andAvatarIsNull() {
                        addCriterion("avatar is null");
                        return (Criteria) this;
                }

                public Criteria andAvatarIsNotNull() {
                        addCriterion("avatar is not null");
                        return (Criteria) this;
                }

                public Criteria andAvatarEqualTo(String value) {
                        addCriterion("avatar =", value, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarNotEqualTo(String value) {
                        addCriterion("avatar <>", value, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarGreaterThan(String value) {
                        addCriterion("avatar >", value, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarGreaterThanOrEqualTo(String value) {
                        addCriterion("avatar >=", value, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarLessThan(String value) {
                        addCriterion("avatar <", value, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarLessThanOrEqualTo(String value) {
                        addCriterion("avatar <=", value, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarLike(String value) {
                        addCriterion("avatar like", value, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarNotLike(String value) {
                        addCriterion("avatar not like", value, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarIn(List<String> values) {
                        addCriterion("avatar in", values, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarNotIn(List<String> values) {
                        addCriterion("avatar not in", values, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarBetween(String value1, String value2) {
                        addCriterion("avatar between", value1, value2, "avatar");
                        return (Criteria) this;
                }

                public Criteria andAvatarNotBetween(String value1, String value2) {
                        addCriterion("avatar not between", value1, value2, "avatar");
                        return (Criteria) this;
                }

                public Criteria andNoticeIsNull() {
                        addCriterion("notice is null");
                        return (Criteria) this;
                }

                public Criteria andNoticeIsNotNull() {
                        addCriterion("notice is not null");
                        return (Criteria) this;
                }

                public Criteria andNoticeEqualTo(String value) {
                        addCriterion("notice =", value, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeNotEqualTo(String value) {
                        addCriterion("notice <>", value, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeGreaterThan(String value) {
                        addCriterion("notice >", value, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeGreaterThanOrEqualTo(String value) {
                        addCriterion("notice >=", value, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeLessThan(String value) {
                        addCriterion("notice <", value, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeLessThanOrEqualTo(String value) {
                        addCriterion("notice <=", value, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeLike(String value) {
                        addCriterion("notice like", value, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeNotLike(String value) {
                        addCriterion("notice not like", value, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeIn(List<String> values) {
                        addCriterion("notice in", values, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeNotIn(List<String> values) {
                        addCriterion("notice not in", values, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeBetween(String value1, String value2) {
                        addCriterion("notice between", value1, value2, "notice");
                        return (Criteria) this;
                }

                public Criteria andNoticeNotBetween(String value1, String value2) {
                        addCriterion("notice not between", value1, value2, "notice");
                        return (Criteria) this;
                }

                public Criteria andProfileIsNull() {
                        addCriterion("profile is null");
                        return (Criteria) this;
                }

                public Criteria andProfileIsNotNull() {
                        addCriterion("profile is not null");
                        return (Criteria) this;
                }

                public Criteria andProfileEqualTo(String value) {
                        addCriterion("profile =", value, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileNotEqualTo(String value) {
                        addCriterion("profile <>", value, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileGreaterThan(String value) {
                        addCriterion("profile >", value, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileGreaterThanOrEqualTo(String value) {
                        addCriterion("profile >=", value, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileLessThan(String value) {
                        addCriterion("profile <", value, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileLessThanOrEqualTo(String value) {
                        addCriterion("profile <=", value, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileLike(String value) {
                        addCriterion("profile like", value, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileNotLike(String value) {
                        addCriterion("profile not like", value, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileIn(List<String> values) {
                        addCriterion("profile in", values, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileNotIn(List<String> values) {
                        addCriterion("profile not in", values, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileBetween(String value1, String value2) {
                        addCriterion("profile between", value1, value2, "profile");
                        return (Criteria) this;
                }

                public Criteria andProfileNotBetween(String value1, String value2) {
                        addCriterion("profile not between", value1, value2, "profile");
                        return (Criteria) this;
                }

                public Criteria andLabelsIsNull() {
                        addCriterion("labels is null");
                        return (Criteria) this;
                }

                public Criteria andLabelsIsNotNull() {
                        addCriterion("labels is not null");
                        return (Criteria) this;
                }

                public Criteria andLabelsEqualTo(String value) {
                        addCriterion("labels =", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsNotEqualTo(String value) {
                        addCriterion("labels <>", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsGreaterThan(String value) {
                        addCriterion("labels >", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsGreaterThanOrEqualTo(String value) {
                        addCriterion("labels >=", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsLessThan(String value) {
                        addCriterion("labels <", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsLessThanOrEqualTo(String value) {
                        addCriterion("labels <=", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsLike(String value) {
                        addCriterion("labels like", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsNotLike(String value) {
                        addCriterion("labels not like", value, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsIn(List<String> values) {
                        addCriterion("labels in", values, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsNotIn(List<String> values) {
                        addCriterion("labels not in", values, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsBetween(String value1, String value2) {
                        addCriterion("labels between", value1, value2, "labels");
                        return (Criteria) this;
                }

                public Criteria andLabelsNotBetween(String value1, String value2) {
                        addCriterion("labels not between", value1, value2, "labels");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankIsNull() {
                        addCriterion("history_rank is null");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankIsNotNull() {
                        addCriterion("history_rank is not null");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankEqualTo(String value) {
                        addCriterion("history_rank =", value, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankNotEqualTo(String value) {
                        addCriterion("history_rank <>", value, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankGreaterThan(String value) {
                        addCriterion("history_rank >", value, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankGreaterThanOrEqualTo(String value) {
                        addCriterion("history_rank >=", value, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankLessThan(String value) {
                        addCriterion("history_rank <", value, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankLessThanOrEqualTo(String value) {
                        addCriterion("history_rank <=", value, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankLike(String value) {
                        addCriterion("history_rank like", value, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankNotLike(String value) {
                        addCriterion("history_rank not like", value, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankIn(List<String> values) {
                        addCriterion("history_rank in", values, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankNotIn(List<String> values) {
                        addCriterion("history_rank not in", values, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankBetween(String value1, String value2) {
                        addCriterion("history_rank between", value1, value2, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryRankNotBetween(String value1, String value2) {
                        addCriterion("history_rank not between", value1, value2, "historyRank");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketIsNull() {
                        addCriterion("history_ticket is null");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketIsNotNull() {
                        addCriterion("history_ticket is not null");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketEqualTo(String value) {
                        addCriterion("history_ticket =", value, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketNotEqualTo(String value) {
                        addCriterion("history_ticket <>", value, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketGreaterThan(String value) {
                        addCriterion("history_ticket >", value, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketGreaterThanOrEqualTo(String value) {
                        addCriterion("history_ticket >=", value, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketLessThan(String value) {
                        addCriterion("history_ticket <", value, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketLessThanOrEqualTo(String value) {
                        addCriterion("history_ticket <=", value, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketLike(String value) {
                        addCriterion("history_ticket like", value, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketNotLike(String value) {
                        addCriterion("history_ticket not like", value, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketIn(List<String> values) {
                        addCriterion("history_ticket in", values, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketNotIn(List<String> values) {
                        addCriterion("history_ticket not in", values, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketBetween(String value1, String value2) {
                        addCriterion("history_ticket between", value1, value2, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andHistoryTicketNotBetween(String value1, String value2) {
                        addCriterion("history_ticket not between", value1, value2, "historyTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketIsNull() {
                        addCriterion("day_ticket is null");
                        return (Criteria) this;
                }

                public Criteria andDayTicketIsNotNull() {
                        addCriterion("day_ticket is not null");
                        return (Criteria) this;
                }

                public Criteria andDayTicketEqualTo(Integer value) {
                        addCriterion("day_ticket =", value, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketNotEqualTo(Integer value) {
                        addCriterion("day_ticket <>", value, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketGreaterThan(Integer value) {
                        addCriterion("day_ticket >", value, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketGreaterThanOrEqualTo(Integer value) {
                        addCriterion("day_ticket >=", value, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketLessThan(Integer value) {
                        addCriterion("day_ticket <", value, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketLessThanOrEqualTo(Integer value) {
                        addCriterion("day_ticket <=", value, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketIn(List<Integer> values) {
                        addCriterion("day_ticket in", values, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketNotIn(List<Integer> values) {
                        addCriterion("day_ticket not in", values, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketBetween(Integer value1, Integer value2) {
                        addCriterion("day_ticket between", value1, value2, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andDayTicketNotBetween(Integer value1, Integer value2) {
                        addCriterion("day_ticket not between", value1, value2, "dayTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketIsNull() {
                        addCriterion("week_ticket is null");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketIsNotNull() {
                        addCriterion("week_ticket is not null");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketEqualTo(Integer value) {
                        addCriterion("week_ticket =", value, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketNotEqualTo(Integer value) {
                        addCriterion("week_ticket <>", value, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketGreaterThan(Integer value) {
                        addCriterion("week_ticket >", value, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketGreaterThanOrEqualTo(Integer value) {
                        addCriterion("week_ticket >=", value, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketLessThan(Integer value) {
                        addCriterion("week_ticket <", value, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketLessThanOrEqualTo(Integer value) {
                        addCriterion("week_ticket <=", value, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketIn(List<Integer> values) {
                        addCriterion("week_ticket in", values, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketNotIn(List<Integer> values) {
                        addCriterion("week_ticket not in", values, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketBetween(Integer value1, Integer value2) {
                        addCriterion("week_ticket between", value1, value2, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andWeekTicketNotBetween(Integer value1, Integer value2) {
                        addCriterion("week_ticket not between", value1, value2, "weekTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketIsNull() {
                        addCriterion("all_ticket is null");
                        return (Criteria) this;
                }

                public Criteria andAllTicketIsNotNull() {
                        addCriterion("all_ticket is not null");
                        return (Criteria) this;
                }

                public Criteria andAllTicketEqualTo(Integer value) {
                        addCriterion("all_ticket =", value, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketNotEqualTo(Integer value) {
                        addCriterion("all_ticket <>", value, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketGreaterThan(Integer value) {
                        addCriterion("all_ticket >", value, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketGreaterThanOrEqualTo(Integer value) {
                        addCriterion("all_ticket >=", value, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketLessThan(Integer value) {
                        addCriterion("all_ticket <", value, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketLessThanOrEqualTo(Integer value) {
                        addCriterion("all_ticket <=", value, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketIn(List<Integer> values) {
                        addCriterion("all_ticket in", values, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketNotIn(List<Integer> values) {
                        addCriterion("all_ticket not in", values, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketBetween(Integer value1, Integer value2) {
                        addCriterion("all_ticket between", value1, value2, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andAllTicketNotBetween(Integer value1, Integer value2) {
                        addCriterion("all_ticket not between", value1, value2, "allTicket");
                        return (Criteria) this;
                }

                public Criteria andTicketIsNull() {
                        addCriterion("ticket is null");
                        return (Criteria) this;
                }

                public Criteria andTicketIsNotNull() {
                        addCriterion("ticket is not null");
                        return (Criteria) this;
                }

                public Criteria andTicketEqualTo(Integer value) {
                        addCriterion("ticket =", value, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketNotEqualTo(Integer value) {
                        addCriterion("ticket <>", value, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketGreaterThan(Integer value) {
                        addCriterion("ticket >", value, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketGreaterThanOrEqualTo(Integer value) {
                        addCriterion("ticket >=", value, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketLessThan(Integer value) {
                        addCriterion("ticket <", value, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketLessThanOrEqualTo(Integer value) {
                        addCriterion("ticket <=", value, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketIn(List<Integer> values) {
                        addCriterion("ticket in", values, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketNotIn(List<Integer> values) {
                        addCriterion("ticket not in", values, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketBetween(Integer value1, Integer value2) {
                        addCriterion("ticket between", value1, value2, "ticket");
                        return (Criteria) this;
                }

                public Criteria andTicketNotBetween(Integer value1, Integer value2) {
                        addCriterion("ticket not between", value1, value2, "ticket");
                        return (Criteria) this;
                }

                public Criteria andMoneyIsNull() {
                        addCriterion("money is null");
                        return (Criteria) this;
                }

                public Criteria andMoneyIsNotNull() {
                        addCriterion("money is not null");
                        return (Criteria) this;
                }

                public Criteria andMoneyEqualTo(Integer value) {
                        addCriterion("money =", value, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyNotEqualTo(Integer value) {
                        addCriterion("money <>", value, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyGreaterThan(Integer value) {
                        addCriterion("money >", value, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyGreaterThanOrEqualTo(Integer value) {
                        addCriterion("money >=", value, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyLessThan(Integer value) {
                        addCriterion("money <", value, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyLessThanOrEqualTo(Integer value) {
                        addCriterion("money <=", value, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyIn(List<Integer> values) {
                        addCriterion("money in", values, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyNotIn(List<Integer> values) {
                        addCriterion("money not in", values, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyBetween(Integer value1, Integer value2) {
                        addCriterion("money between", value1, value2, "money");
                        return (Criteria) this;
                }

                public Criteria andMoneyNotBetween(Integer value1, Integer value2) {
                        addCriterion("money not between", value1, value2, "money");
                        return (Criteria) this;
                }

                public Criteria andPayCountIsNull() {
                        addCriterion("pay_count is null");
                        return (Criteria) this;
                }

                public Criteria andPayCountIsNotNull() {
                        addCriterion("pay_count is not null");
                        return (Criteria) this;
                }

                public Criteria andPayCountEqualTo(Integer value) {
                        addCriterion("pay_count =", value, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountNotEqualTo(Integer value) {
                        addCriterion("pay_count <>", value, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountGreaterThan(Integer value) {
                        addCriterion("pay_count >", value, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("pay_count >=", value, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountLessThan(Integer value) {
                        addCriterion("pay_count <", value, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountLessThanOrEqualTo(Integer value) {
                        addCriterion("pay_count <=", value, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountIn(List<Integer> values) {
                        addCriterion("pay_count in", values, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountNotIn(List<Integer> values) {
                        addCriterion("pay_count not in", values, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountBetween(Integer value1, Integer value2) {
                        addCriterion("pay_count between", value1, value2, "payCount");
                        return (Criteria) this;
                }

                public Criteria andPayCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("pay_count not between", value1, value2, "payCount");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlIsNull() {
                        addCriterion("attestation_url is null");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlIsNotNull() {
                        addCriterion("attestation_url is not null");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlEqualTo(String value) {
                        addCriterion("attestation_url =", value, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlNotEqualTo(String value) {
                        addCriterion("attestation_url <>", value, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlGreaterThan(String value) {
                        addCriterion("attestation_url >", value, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlGreaterThanOrEqualTo(String value) {
                        addCriterion("attestation_url >=", value, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlLessThan(String value) {
                        addCriterion("attestation_url <", value, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlLessThanOrEqualTo(String value) {
                        addCriterion("attestation_url <=", value, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlLike(String value) {
                        addCriterion("attestation_url like", value, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlNotLike(String value) {
                        addCriterion("attestation_url not like", value, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlIn(List<String> values) {
                        addCriterion("attestation_url in", values, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlNotIn(List<String> values) {
                        addCriterion("attestation_url not in", values, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlBetween(String value1, String value2) {
                        addCriterion("attestation_url between", value1, value2, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andAttestationUrlNotBetween(String value1, String value2) {
                        addCriterion("attestation_url not between", value1, value2, "attestationUrl");
                        return (Criteria) this;
                }

                public Criteria andLikeCountIsNull() {
                        addCriterion("like_count is null");
                        return (Criteria) this;
                }

                public Criteria andLikeCountIsNotNull() {
                        addCriterion("like_count is not null");
                        return (Criteria) this;
                }

                public Criteria andLikeCountEqualTo(Integer value) {
                        addCriterion("like_count =", value, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountNotEqualTo(Integer value) {
                        addCriterion("like_count <>", value, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountGreaterThan(Integer value) {
                        addCriterion("like_count >", value, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("like_count >=", value, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountLessThan(Integer value) {
                        addCriterion("like_count <", value, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountLessThanOrEqualTo(Integer value) {
                        addCriterion("like_count <=", value, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountIn(List<Integer> values) {
                        addCriterion("like_count in", values, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountNotIn(List<Integer> values) {
                        addCriterion("like_count not in", values, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountBetween(Integer value1, Integer value2) {
                        addCriterion("like_count between", value1, value2, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andLikeCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("like_count not between", value1, value2, "likeCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountIsNull() {
                        addCriterion("forward_count is null");
                        return (Criteria) this;
                }

                public Criteria andForwardCountIsNotNull() {
                        addCriterion("forward_count is not null");
                        return (Criteria) this;
                }

                public Criteria andForwardCountEqualTo(Integer value) {
                        addCriterion("forward_count =", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountNotEqualTo(Integer value) {
                        addCriterion("forward_count <>", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountGreaterThan(Integer value) {
                        addCriterion("forward_count >", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("forward_count >=", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountLessThan(Integer value) {
                        addCriterion("forward_count <", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountLessThanOrEqualTo(Integer value) {
                        addCriterion("forward_count <=", value, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountIn(List<Integer> values) {
                        addCriterion("forward_count in", values, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountNotIn(List<Integer> values) {
                        addCriterion("forward_count not in", values, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountBetween(Integer value1, Integer value2) {
                        addCriterion("forward_count between", value1, value2, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andForwardCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("forward_count not between", value1, value2, "forwardCount");
                        return (Criteria) this;
                }

                public Criteria andIsSystemIsNull() {
                        addCriterion("is_system is null");
                        return (Criteria) this;
                }

                public Criteria andIsSystemIsNotNull() {
                        addCriterion("is_system is not null");
                        return (Criteria) this;
                }

                public Criteria andIsSystemEqualTo(Boolean value) {
                        addCriterion("is_system =", value, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemNotEqualTo(Boolean value) {
                        addCriterion("is_system <>", value, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemGreaterThan(Boolean value) {
                        addCriterion("is_system >", value, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemGreaterThanOrEqualTo(Boolean value) {
                        addCriterion("is_system >=", value, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemLessThan(Boolean value) {
                        addCriterion("is_system <", value, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemLessThanOrEqualTo(Boolean value) {
                        addCriterion("is_system <=", value, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemIn(List<Boolean> values) {
                        addCriterion("is_system in", values, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemNotIn(List<Boolean> values) {
                        addCriterion("is_system not in", values, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemBetween(Boolean value1, Boolean value2) {
                        addCriterion("is_system between", value1, value2, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andIsSystemNotBetween(Boolean value1, Boolean value2) {
                        addCriterion("is_system not between", value1, value2, "isSystem");
                        return (Criteria) this;
                }

                public Criteria andCityAddressIsNull() {
                        addCriterion("city_address is null");
                        return (Criteria) this;
                }

                public Criteria andCityAddressIsNotNull() {
                        addCriterion("city_address is not null");
                        return (Criteria) this;
                }

                public Criteria andCityAddressEqualTo(String value) {
                        addCriterion("city_address =", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressNotEqualTo(String value) {
                        addCriterion("city_address <>", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressGreaterThan(String value) {
                        addCriterion("city_address >", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressGreaterThanOrEqualTo(String value) {
                        addCriterion("city_address >=", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressLessThan(String value) {
                        addCriterion("city_address <", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressLessThanOrEqualTo(String value) {
                        addCriterion("city_address <=", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressLike(String value) {
                        addCriterion("city_address like", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressNotLike(String value) {
                        addCriterion("city_address not like", value, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressIn(List<String> values) {
                        addCriterion("city_address in", values, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressNotIn(List<String> values) {
                        addCriterion("city_address not in", values, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressBetween(String value1, String value2) {
                        addCriterion("city_address between", value1, value2, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andCityAddressNotBetween(String value1, String value2) {
                        addCriterion("city_address not between", value1, value2, "cityAddress");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountIsNull() {
                        addCriterion("day_vote_count is null");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountIsNotNull() {
                        addCriterion("day_vote_count is not null");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountEqualTo(Integer value) {
                        addCriterion("day_vote_count =", value, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountNotEqualTo(Integer value) {
                        addCriterion("day_vote_count <>", value, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountGreaterThan(Integer value) {
                        addCriterion("day_vote_count >", value, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("day_vote_count >=", value, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountLessThan(Integer value) {
                        addCriterion("day_vote_count <", value, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountLessThanOrEqualTo(Integer value) {
                        addCriterion("day_vote_count <=", value, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountIn(List<Integer> values) {
                        addCriterion("day_vote_count in", values, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountNotIn(List<Integer> values) {
                        addCriterion("day_vote_count not in", values, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountBetween(Integer value1, Integer value2) {
                        addCriterion("day_vote_count between", value1, value2, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andDayVoteCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("day_vote_count not between", value1, value2, "dayVoteCount");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIsNull() {
                        addCriterion("create_time is null");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIsNotNull() {
                        addCriterion("create_time is not null");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeEqualTo(Date value) {
                        addCriterion("create_time =", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotEqualTo(Date value) {
                        addCriterion("create_time <>", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeGreaterThan(Date value) {
                        addCriterion("create_time >", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
                        addCriterion("create_time >=", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeLessThan(Date value) {
                        addCriterion("create_time <", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
                        addCriterion("create_time <=", value, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeIn(List<Date> values) {
                        addCriterion("create_time in", values, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotIn(List<Date> values) {
                        addCriterion("create_time not in", values, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeBetween(Date value1, Date value2) {
                        addCriterion("create_time between", value1, value2, "createTime");
                        return (Criteria) this;
                }

                public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
                        addCriterion("create_time not between", value1, value2, "createTime");
                        return (Criteria) this;
                }

                public Criteria andStatusIsNull() {
                        addCriterion("status is null");
                        return (Criteria) this;
                }

                public Criteria andStatusIsNotNull() {
                        addCriterion("status is not null");
                        return (Criteria) this;
                }

                public Criteria andStatusEqualTo(Byte value) {
                        addCriterion("status =", value, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusNotEqualTo(Byte value) {
                        addCriterion("status <>", value, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusGreaterThan(Byte value) {
                        addCriterion("status >", value, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
                        addCriterion("status >=", value, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusLessThan(Byte value) {
                        addCriterion("status <", value, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusLessThanOrEqualTo(Byte value) {
                        addCriterion("status <=", value, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusIn(List<Byte> values) {
                        addCriterion("status in", values, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusNotIn(List<Byte> values) {
                        addCriterion("status not in", values, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusBetween(Byte value1, Byte value2) {
                        addCriterion("status between", value1, value2, "status");
                        return (Criteria) this;
                }

                public Criteria andStatusNotBetween(Byte value1, Byte value2) {
                        addCriterion("status not between", value1, value2, "status");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountIsNull() {
                        addCriterion("question_count is null");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountIsNotNull() {
                        addCriterion("question_count is not null");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountEqualTo(Integer value) {
                        addCriterion("question_count =", value, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountNotEqualTo(Integer value) {
                        addCriterion("question_count <>", value, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountGreaterThan(Integer value) {
                        addCriterion("question_count >", value, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("question_count >=", value, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountLessThan(Integer value) {
                        addCriterion("question_count <", value, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountLessThanOrEqualTo(Integer value) {
                        addCriterion("question_count <=", value, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountIn(List<Integer> values) {
                        addCriterion("question_count in", values, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountNotIn(List<Integer> values) {
                        addCriterion("question_count not in", values, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountBetween(Integer value1, Integer value2) {
                        addCriterion("question_count between", value1, value2, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andQuestionCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("question_count not between", value1, value2, "questionCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountIsNull() {
                        addCriterion("answer_count is null");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountIsNotNull() {
                        addCriterion("answer_count is not null");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountEqualTo(Integer value) {
                        addCriterion("answer_count =", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountNotEqualTo(Integer value) {
                        addCriterion("answer_count <>", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountGreaterThan(Integer value) {
                        addCriterion("answer_count >", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("answer_count >=", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountLessThan(Integer value) {
                        addCriterion("answer_count <", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountLessThanOrEqualTo(Integer value) {
                        addCriterion("answer_count <=", value, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountIn(List<Integer> values) {
                        addCriterion("answer_count in", values, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountNotIn(List<Integer> values) {
                        addCriterion("answer_count not in", values, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountBetween(Integer value1, Integer value2) {
                        addCriterion("answer_count between", value1, value2, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andAnswerCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("answer_count not between", value1, value2, "answerCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountIsNull() {
                        addCriterion("comment_count is null");
                        return (Criteria) this;
                }

                public Criteria andCommentCountIsNotNull() {
                        addCriterion("comment_count is not null");
                        return (Criteria) this;
                }

                public Criteria andCommentCountEqualTo(Integer value) {
                        addCriterion("comment_count =", value, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountNotEqualTo(Integer value) {
                        addCriterion("comment_count <>", value, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountGreaterThan(Integer value) {
                        addCriterion("comment_count >", value, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("comment_count >=", value, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountLessThan(Integer value) {
                        addCriterion("comment_count <", value, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountLessThanOrEqualTo(Integer value) {
                        addCriterion("comment_count <=", value, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountIn(List<Integer> values) {
                        addCriterion("comment_count in", values, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountNotIn(List<Integer> values) {
                        addCriterion("comment_count not in", values, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountBetween(Integer value1, Integer value2) {
                        addCriterion("comment_count between", value1, value2, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andCommentCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("comment_count not between", value1, value2, "commentCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountIsNull() {
                        addCriterion("reply_count is null");
                        return (Criteria) this;
                }

                public Criteria andReplyCountIsNotNull() {
                        addCriterion("reply_count is not null");
                        return (Criteria) this;
                }

                public Criteria andReplyCountEqualTo(Integer value) {
                        addCriterion("reply_count =", value, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountNotEqualTo(Integer value) {
                        addCriterion("reply_count <>", value, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountGreaterThan(Integer value) {
                        addCriterion("reply_count >", value, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountGreaterThanOrEqualTo(Integer value) {
                        addCriterion("reply_count >=", value, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountLessThan(Integer value) {
                        addCriterion("reply_count <", value, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountLessThanOrEqualTo(Integer value) {
                        addCriterion("reply_count <=", value, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountIn(List<Integer> values) {
                        addCriterion("reply_count in", values, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountNotIn(List<Integer> values) {
                        addCriterion("reply_count not in", values, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountBetween(Integer value1, Integer value2) {
                        addCriterion("reply_count between", value1, value2, "replyCount");
                        return (Criteria) this;
                }

                public Criteria andReplyCountNotBetween(Integer value1, Integer value2) {
                        addCriterion("reply_count not between", value1, value2, "replyCount");
                        return (Criteria) this;
                }
        }

        /**
         * This class was generated by MyBatis Generator. This class corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public static class Criterion {
                private String condition;
                private Object value;
                private Object secondValue;
                private boolean noValue;
                private boolean singleValue;
                private boolean betweenValue;
                private boolean listValue;
                private String typeHandler;

                public String getCondition() {
                        return condition;
                }

                public Object getValue() {
                        return value;
                }

                public Object getSecondValue() {
                        return secondValue;
                }

                public boolean isNoValue() {
                        return noValue;
                }

                public boolean isSingleValue() {
                        return singleValue;
                }

                public boolean isBetweenValue() {
                        return betweenValue;
                }

                public boolean isListValue() {
                        return listValue;
                }

                public String getTypeHandler() {
                        return typeHandler;
                }

                protected Criterion(String condition) {
                        super();
                        this.condition = condition;
                        this.typeHandler = null;
                        this.noValue = true;
                }

                protected Criterion(String condition, Object value, String typeHandler) {
                        super();
                        this.condition = condition;
                        this.value = value;
                        this.typeHandler = typeHandler;
                        if (value instanceof List<?>) {
                                this.listValue = true;
                        } else {
                                this.singleValue = true;
                        }
                }

                protected Criterion(String condition, Object value) {
                        this(condition, value, null);
                }

                protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
                        super();
                        this.condition = condition;
                        this.value = value;
                        this.secondValue = secondValue;
                        this.typeHandler = typeHandler;
                        this.betweenValue = true;
                }

                protected Criterion(String condition, Object value, Object secondValue) {
                        this(condition, value, secondValue, null);
                }
        }

/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 21 14:32:55 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}