package com.ayue.sp.db.po;

import java.util.Date;

public class User2subject {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user2subject.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user2subject.subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer subjectId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user2subject.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user2subject.user_id
         * @return  the value of user2subject.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user2subject.user_id
         * @param userId  the value for user2subject.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user2subject.subject_id
         * @return  the value of user2subject.subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getSubjectId() {
                return subjectId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user2subject.subject_id
         * @param subjectId  the value for user2subject.subject_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setSubjectId(Integer subjectId) {
                this.subjectId = subjectId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user2subject.create_time
         * @return  the value of user2subject.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user2subject.create_time
         * @param createTime  the value for user2subject.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}