package com.ayue.sp.db.po;

import java.util.Date;

public class UserLoginRecord {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_login_record.user_id
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_login_record.login_time
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        private Date loginTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_login_record.duration
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        private Long duration;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_login_record.user_id
         * @return  the value of user_login_record.user_id
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_login_record.user_id
         * @param userId  the value for user_login_record.user_id
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_login_record.login_time
         * @return  the value of user_login_record.login_time
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        public Date getLoginTime() {
                return loginTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_login_record.login_time
         * @param loginTime  the value for user_login_record.login_time
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        public void setLoginTime(Date loginTime) {
                this.loginTime = loginTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_login_record.duration
         * @return  the value of user_login_record.duration
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        public Long getDuration() {
                return duration;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_login_record.duration
         * @param duration  the value for user_login_record.duration
         * @mbg.generated  Wed Oct 07 16:43:44 CST 2020
         */
        public void setDuration(Long duration) {
                this.duration = duration;
        }
}