package com.ayue.sp.db.po;

import java.util.Date;

public class UserTipoffs {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_tipoffs.target_user_id
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        private Integer targetUserId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_tipoffs.user_id
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_tipoffs.type
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        private Byte type;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_tipoffs.description
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        private String description;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_tipoffs.picture_url
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        private String pictureUrl;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_tipoffs.create_time
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_tipoffs.is_dealed
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        private Boolean isDealed;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_tipoffs.target_user_id
         * @return  the value of user_tipoffs.target_user_id
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public Integer getTargetUserId() {
                return targetUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_tipoffs.target_user_id
         * @param targetUserId  the value for user_tipoffs.target_user_id
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setTargetUserId(Integer targetUserId) {
                this.targetUserId = targetUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_tipoffs.user_id
         * @return  the value of user_tipoffs.user_id
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_tipoffs.user_id
         * @param userId  the value for user_tipoffs.user_id
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_tipoffs.type
         * @return  the value of user_tipoffs.type
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public Byte getType() {
                return type;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_tipoffs.type
         * @param type  the value for user_tipoffs.type
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setType(Byte type) {
                this.type = type;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_tipoffs.description
         * @return  the value of user_tipoffs.description
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public String getDescription() {
                return description;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_tipoffs.description
         * @param description  the value for user_tipoffs.description
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setDescription(String description) {
                this.description = description;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_tipoffs.picture_url
         * @return  the value of user_tipoffs.picture_url
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public String getPictureUrl() {
                return pictureUrl;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_tipoffs.picture_url
         * @param pictureUrl  the value for user_tipoffs.picture_url
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setPictureUrl(String pictureUrl) {
                this.pictureUrl = pictureUrl;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_tipoffs.create_time
         * @return  the value of user_tipoffs.create_time
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_tipoffs.create_time
         * @param createTime  the value for user_tipoffs.create_time
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_tipoffs.is_dealed
         * @return  the value of user_tipoffs.is_dealed
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public Boolean getIsDealed() {
                return isDealed;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_tipoffs.is_dealed
         * @param isDealed  the value for user_tipoffs.is_dealed
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        public void setIsDealed(Boolean isDealed) {
                this.isDealed = isDealed;
        }
}