package com.ayue.sp.db.po;

import java.util.Date;

public class UserReplyAgree {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_reply_agree.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_reply_agree.reply_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Integer replyId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user_reply_agree.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        private Date createTime;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_reply_agree.user_id
         * @return  the value of user_reply_agree.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_reply_agree.user_id
         * @param userId  the value for user_reply_agree.user_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_reply_agree.reply_id
         * @return  the value of user_reply_agree.reply_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Integer getReplyId() {
                return replyId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_reply_agree.reply_id
         * @param replyId  the value for user_reply_agree.reply_id
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setReplyId(Integer replyId) {
                this.replyId = replyId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user_reply_agree.create_time
         * @return  the value of user_reply_agree.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user_reply_agree.create_time
         * @param createTime  the value for user_reply_agree.create_time
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }
}