package com.ayue.sp.db.po;

import java.util.Date;

public class User2visited {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user2visited.question_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        private Integer questionId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user2visited.target_user_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        private Integer targetUserId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user2visited.user_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        private Integer userId;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user2visited.create_time
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user2visited.is_finish
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        private Boolean isFinish;

        private Integer type;

        public Boolean getFinish() {
                return isFinish;
        }

        public void setFinish(Boolean finish) {
                isFinish = finish;
        }

        public Integer getType() {
                return type;
        }

        public void setType(Integer type) {
                this.type = type;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user2visited.question_id
         * @return  the value of user2visited.question_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public Integer getQuestionId() {
                return questionId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user2visited.question_id
         * @param questionId  the value for user2visited.question_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public void setQuestionId(Integer questionId) {
                this.questionId = questionId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user2visited.target_user_id
         * @return  the value of user2visited.target_user_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public Integer getTargetUserId() {
                return targetUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user2visited.target_user_id
         * @param targetUserId  the value for user2visited.target_user_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public void setTargetUserId(Integer targetUserId) {
                this.targetUserId = targetUserId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user2visited.user_id
         * @return  the value of user2visited.user_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public Integer getUserId() {
                return userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user2visited.user_id
         * @param userId  the value for user2visited.user_id
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public void setUserId(Integer userId) {
                this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user2visited.create_time
         * @return  the value of user2visited.create_time
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user2visited.create_time
         * @param createTime  the value for user2visited.create_time
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user2visited.is_finish
         * @return  the value of user2visited.is_finish
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public Boolean getIsFinish() {
                return isFinish;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user2visited.is_finish
         * @param isFinish  the value for user2visited.is_finish
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        public void setIsFinish(Boolean isFinish) {
                this.isFinish = isFinish;
        }
}