package com.ayue.sp.db.po;

import java.util.Date;

public class User {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.openId
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String openid;

        private String professional;

        private Integer level;

        private String proficient;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Byte gender;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String name;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.avatar
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String avatar;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.notice
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String notice;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.profile
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String profile;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.labels
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String labels;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.history_rank
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String historyRank;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.history_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String historyTicket;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.day_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer dayTicket;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.week_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer weekTicket;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.all_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer allTicket;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer ticket;

        private Integer obtainTicket;
        private Integer obtainTicketAll;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.money
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer money;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.pay_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer payCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.attestation_url
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String attestationUrl;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.like_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer likeCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.forward_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer forwardCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.is_system
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Boolean isSystem;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.city_address
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String cityAddress;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.day_vote_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer dayVoteCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Date createTime;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Byte status;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.question_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer questionCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.answer_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer answerCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.comment_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer commentCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.reply_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private Integer replyCount;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column user.reply_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        private String password;

        private String city;

        private Integer identity;

        private String unit;

        private Integer energyBean;

        private Integer teacher;

        private Integer rankEnergyBean;

        public Integer getRankEnergyBean() {
                return rankEnergyBean;
        }

        public void setRankEnergyBean(Integer rankEnergyBean) {
                this.rankEnergyBean = rankEnergyBean;
        }

        public Integer getTeacher() {
            return teacher;
        }

        public void setTeacher(Integer teacher) {
            this.teacher = teacher;
        }

        public Integer getEnergyBean() {
            return energyBean;
        }

        public void setEnergyBean(Integer energyBean) {
            this.energyBean = energyBean;
        }

        public Integer getIdentity() {
                    return identity;
            }

        public void setIdentity(Integer identity) {
                this.identity = identity;
        }

        public String getUnit() {
                return unit;
        }

        public void setUnit(String unit) {
                this.unit = unit;
        }

        public String getCity() {
                return city;
        }

        public void setCity(String city) {
                this.city = city;
        }

        public Integer getObtainTicketAll() {
                return obtainTicketAll;
        }

        public void setObtainTicketAll(Integer obtainTicketAll) {
                this.obtainTicketAll = obtainTicketAll;
        }

        public Integer getLevel() {
                return level;
        }

        public void setLevel(Integer level) {
                this.level = level;
        }

        public Boolean getSystem() {
                return isSystem;
        }

        public void setSystem(Boolean system) {
                isSystem = system;
        }

        public String getProfessional() {
                return professional;
        }

        public void setProfessional(String professional) {
                this.professional = professional;
        }

        public String getProficient() {
                return proficient;
        }

        public void setProficient(String proficient) {
                this.proficient = proficient;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
         * @return  the value of user.id
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getPassword() {
                return password;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
         * @param password  the value for user.id
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setPassword(String password) {
                this.password = password;
        }

        public Integer getObtainTicket() {
                return obtainTicket;
        }

        public void setObtainTicket(Integer obtainTicket) {
                this.obtainTicket = obtainTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
         * @return  the value of user.id
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
         * @param id  the value for user.id
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setId(Integer id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.openId
         * @return  the value of user.openId
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getOpenid() {
                return openid;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.openId
         * @param openid  the value for user.openId
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setOpenid(String openid) {
                this.openid = openid;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
         * @return  the value of user.gender
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Byte getGender() {
                return gender;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
         * @param gender  the value for user.gender
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setGender(Byte gender) {
                this.gender = gender;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
         * @return  the value of user.name
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getName() {
                return name;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
         * @param name  the value for user.name
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setName(String name) {
                this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.avatar
         * @return  the value of user.avatar
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getAvatar() {
                return avatar;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.avatar
         * @param avatar  the value for user.avatar
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setAvatar(String avatar) {
                this.avatar = avatar;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.notice
         * @return  the value of user.notice
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getNotice() {
                return notice;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.notice
         * @param notice  the value for user.notice
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setNotice(String notice) {
                this.notice = notice;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.profile
         * @return  the value of user.profile
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getProfile() {
                return profile;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.profile
         * @param profile  the value for user.profile
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setProfile(String profile) {
                this.profile = profile;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.labels
         * @return  the value of user.labels
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getLabels() {
                return labels;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.labels
         * @param labels  the value for user.labels
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setLabels(String labels) {
                this.labels = labels;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.history_rank
         * @return  the value of user.history_rank
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getHistoryRank() {
                return historyRank;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.history_rank
         * @param historyRank  the value for user.history_rank
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setHistoryRank(String historyRank) {
                this.historyRank = historyRank;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.history_ticket
         * @return  the value of user.history_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getHistoryTicket() {
                return historyTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.history_ticket
         * @param historyTicket  the value for user.history_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setHistoryTicket(String historyTicket) {
                this.historyTicket = historyTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.day_ticket
         * @return  the value of user.day_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getDayTicket() {
                return dayTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.day_ticket
         * @param dayTicket  the value for user.day_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setDayTicket(Integer dayTicket) {
                this.dayTicket = dayTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.week_ticket
         * @return  the value of user.week_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getWeekTicket() {
                return weekTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.week_ticket
         * @param weekTicket  the value for user.week_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setWeekTicket(Integer weekTicket) {
                this.weekTicket = weekTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.all_ticket
         * @return  the value of user.all_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getAllTicket() {
                return allTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.all_ticket
         * @param allTicket  the value for user.all_ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setAllTicket(Integer allTicket) {
                this.allTicket = allTicket;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.ticket
         * @return  the value of user.ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getTicket() {
                return ticket;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.ticket
         * @param ticket  the value for user.ticket
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setTicket(Integer ticket) {
                this.ticket = ticket;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.money
         * @return  the value of user.money
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getMoney() {
                return money;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.money
         * @param money  the value for user.money
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setMoney(Integer money) {
                this.money = money;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.pay_count
         * @return  the value of user.pay_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getPayCount() {
                return payCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.pay_count
         * @param payCount  the value for user.pay_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setPayCount(Integer payCount) {
                this.payCount = payCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.attestation_url
         * @return  the value of user.attestation_url
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getAttestationUrl() {
                return attestationUrl;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.attestation_url
         * @param attestationUrl  the value for user.attestation_url
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setAttestationUrl(String attestationUrl) {
                this.attestationUrl = attestationUrl;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.like_count
         * @return  the value of user.like_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getLikeCount() {
                return likeCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.like_count
         * @param likeCount  the value for user.like_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setLikeCount(Integer likeCount) {
                this.likeCount = likeCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.forward_count
         * @return  the value of user.forward_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getForwardCount() {
                return forwardCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.forward_count
         * @param forwardCount  the value for user.forward_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setForwardCount(Integer forwardCount) {
                this.forwardCount = forwardCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.is_system
         * @return  the value of user.is_system
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Boolean getIsSystem() {
                return isSystem;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.is_system
         * @param isSystem  the value for user.is_system
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setIsSystem(Boolean isSystem) {
                this.isSystem = isSystem;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.city_address
         * @return  the value of user.city_address
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public String getCityAddress() {
                return cityAddress;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.city_address
         * @param cityAddress  the value for user.city_address
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setCityAddress(String cityAddress) {
                this.cityAddress = cityAddress;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.day_vote_count
         * @return  the value of user.day_vote_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getDayVoteCount() {
                return dayVoteCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.day_vote_count
         * @param dayVoteCount  the value for user.day_vote_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setDayVoteCount(Integer dayVoteCount) {
                this.dayVoteCount = dayVoteCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
         * @return  the value of user.create_time
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Date getCreateTime() {
                return createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
         * @param createTime  the value for user.create_time
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setCreateTime(Date createTime) {
                this.createTime = createTime;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
         * @return  the value of user.status
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Byte getStatus() {
                return status;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
         * @param status  the value for user.status
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setStatus(Byte status) {
                this.status = status;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.question_count
         * @return  the value of user.question_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getQuestionCount() {
                return questionCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.question_count
         * @param questionCount  the value for user.question_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setQuestionCount(Integer questionCount) {
                this.questionCount = questionCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.answer_count
         * @return  the value of user.answer_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getAnswerCount() {
                return answerCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.answer_count
         * @param answerCount  the value for user.answer_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setAnswerCount(Integer answerCount) {
                this.answerCount = answerCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.comment_count
         * @return  the value of user.comment_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getCommentCount() {
                return commentCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.comment_count
         * @param commentCount  the value for user.comment_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setCommentCount(Integer commentCount) {
                this.commentCount = commentCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column user.reply_count
         * @return  the value of user.reply_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public Integer getReplyCount() {
                return replyCount;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column user.reply_count
         * @param replyCount  the value for user.reply_count
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        public void setReplyCount(Integer replyCount) {
                this.replyCount = replyCount;
        }
}