package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.AdvertRecord;
import com.ayue.sp.db.po.AdvertRecordExample;

@Repository
public interface AdvertRecordMapper {
        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        long countByExample(AdvertRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        int deleteByExample(AdvertRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        int insert(AdvertRecord record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        int insertSelective(AdvertRecord record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        List<AdvertRecord> selectByExample(AdvertRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        AdvertRecord selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        int updateByExampleSelective(@Param("record") AdvertRecord record, @Param("example") AdvertRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        int updateByExample(@Param("record") AdvertRecord record, @Param("example") AdvertRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        int updateByPrimaryKeySelective(AdvertRecord record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table advert_record
         *
         * @mbg.generated Fri Oct 09 11:49:48 CST 2020
         */
        int updateByPrimaryKey(AdvertRecord record);
}