package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.Answer;
import com.ayue.sp.db.po.AnswerExample;

@Repository
public interface AnswerMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(AnswerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(AnswerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(Answer record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(Answer record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<Answer> selectByExample(AnswerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        Answer selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") Answer record, @Param("example") AnswerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") Answer record, @Param("example") AnswerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(Answer record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table answer
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(Answer record);

        List<Answer> selectMaxClick(@Param(value = "questionIds") String questionIds);

        void addForwardCount(@Param(value = "id") Integer answerId);

        void addCommentCount(Integer answerId);

        void addAgreeCount(@Param(value = "userId")Integer userId,@Param(value = "answerId")Integer answerId);

        void reduceAgreeCount(Integer answerId);
        void updateAnswerTicket(@Param(value = "targetUserId") Integer targetUserId,@Param(value = "ticket")Integer ticket,@Param(value = "answerId")Integer answerId);
        void updateAnswerOnline(@Param(value = "id")Integer answerId);
        void updateAnswerOffline(@Param(value = "id")Integer answerId);
        void updateAnswerAdopt(@Param(value = "answerId")int answerId,@Param(value = "ticket") int ticket);
}