package com.ayue.sp.db.dao;

import com.ayue.sp.db.po.City;
import com.ayue.sp.db.po.Comment;
import com.ayue.sp.db.po.CommentExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CityMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(City record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(City record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        City selectByPrimaryKeyId(Integer id);
        List<City> selectByPrimary();

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(Comment record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(Comment record);

        void addReplyCount(Integer commentId);

        void addAgreeCount(@Param(value = "userId") Integer userId, @Param(value = "commentId") Integer commentId);

        void reduceAgreeCount(Integer commentId);
        void updateCommentOnline(@Param(value = "id") Integer commentId);
        void updateCommentOffline(@Param(value = "id") Integer commentId);
        Integer getCommentUserIdCount(Integer userId);
}