package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.Comment;
import com.ayue.sp.db.po.CommentExample;

@Repository
public interface CommentMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(CommentExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(CommentExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(Comment record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(Comment record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<Comment> selectByExample(CommentExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        Comment selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(Comment record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table comment
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(Comment record);

        void addReplyCount(Integer commentId);

        void addAgreeCount(@Param(value = "userId")Integer userId,@Param(value = "commentId")Integer commentId);

        void reduceAgreeCount(Integer commentId);
        void updateCommentOnline(@Param(value = "id")Integer commentId);
        void updateCommentOffline(@Param(value = "id")Integer commentId);
        Integer getCommentUserIdCount(Integer userId);
}