package com.ayue.sp.db.dao;

import com.ayue.sp.db.po.*;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EnergyBeanMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int insert(EnergyBean record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        EnergyBean selectByPrimaryKey(Integer id);

        List<EnergyBean> selectByExample(EnergyBeanExample example);
        List<EnergyBean> selectByRankExample(EnergyBeanExample example);
        EnergyBean selectByTypeExample(EnergyBeanExample example);


}