package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.IdGeneratorRecorder;
import com.ayue.sp.db.po.IdGeneratorRecorderExample;

@Repository
public interface IdGeneratorRecorderMapper {
        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(IdGeneratorRecorderExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(IdGeneratorRecorderExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(String id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(IdGeneratorRecorder record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(IdGeneratorRecorder record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<IdGeneratorRecorder> selectByExample(IdGeneratorRecorderExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        IdGeneratorRecorder selectByPrimaryKey(String id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") IdGeneratorRecorder record, @Param("example") IdGeneratorRecorderExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") IdGeneratorRecorder record, @Param("example") IdGeneratorRecorderExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(IdGeneratorRecorder record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table id_generator_recorder
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(IdGeneratorRecorder record);

        int updateTargetValue();
}