package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.Question;
import com.ayue.sp.db.po.QuestionExample;

@Repository
public interface QuestionMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(QuestionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(QuestionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(Question record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(Question record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<Question> selectByExample(QuestionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        Question selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(Question record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(Question record);

        List<Question> selectMaxRead(@Param(value = "userIds") String userIds);

        List<Integer> selectMaxIdByOtherSubjectId(@Param(value = "subjectIds") String subjectIds);

        List<Integer> selectMaxIdByRegionSubjectId(@Param(value = "subjectIds") String subjectIds);

        List<Integer> selectMaxIdByCrowdSubjectId(@Param(value = "subjectIds") String subjectIds);

        void addForwardCount(@Param(value = "id") Integer questionId);

        void addCollectionCount(@Param(value = "userId")Integer userId,@Param(value = "questionId")Integer questionId);

        void reduceCollectionCount(Integer questionId);
        void updateQuestionOnline(@Param(value = "id")Integer questionId);
        void updateQuestionOffline(@Param(value = "id")Integer questionId);
        Integer getQuestionUserIdCount(Integer userId);
        void updateQuestionTicket(int questionId);

}