package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.QuestionLinkRecord;
import com.ayue.sp.db.po.QuestionLinkRecordExample;

@Repository
public interface QuestionLinkRecordMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(QuestionLinkRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(QuestionLinkRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(QuestionLinkRecord record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(QuestionLinkRecord record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<QuestionLinkRecord> selectByExample(QuestionLinkRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        QuestionLinkRecord selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") QuestionLinkRecord record, @Param("example") QuestionLinkRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") QuestionLinkRecord record, @Param("example") QuestionLinkRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(QuestionLinkRecord record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table question_link_record
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(QuestionLinkRecord record);
}