package com.ayue.sp.db.dao;

import com.ayue.sp.db.po.TeacherRecord;
import com.ayue.sp.db.po.TeacherRecordExample;
import com.ayue.sp.db.po.User;
import com.ayue.sp.db.po.UserExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Repository
public interface TeacherRecordMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table TeacherRecord
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table TeacherRecord
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int insert(TeacherRecord record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table TeacherRecord
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int insertSelective(TeacherRecord record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table TeacherRecord
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        TeacherRecord selectByPrimaryKey(Integer id);
        
        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table TeacherRecord
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int updateByPrimaryKeySelective(TeacherRecord record);
        int updateTeacherRecords(TeacherRecord record);
        int updateTeacherRecord(List<TeacherRecord> records);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table TeacherRecord
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int updateByPrimaryKey(TeacherRecord record);

        void addForwardCount(Integer TeacherRecordId);
        List<TeacherRecord> selectByExample(TeacherRecordExample example);
        List<TeacherRecord> getTeacherRecordName(List<Integer> collect);
        TeacherRecord getTeacherRecord(@Param("userId") Integer userId, @Param("teacherId") Integer targetUserId,@Param("createTime") Date createTime);
        TeacherRecord getTeacherRecords(@Param("userId") Integer userId, @Param("teacherId") Integer targetUserId,@Param("updateTime") Date updateTime);
        void updateTeacherRecordTicket(@Param("ticket") Integer ticket, @Param("TeacherRecordId") Integer TeacherRecordId);
}