package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserAnswerAgree;
import com.ayue.sp.db.po.UserAnswerAgreeExample;

@Repository
public interface UserAnswerAgreeMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserAnswerAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserAnswerAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("answerId") Integer answerId);
        void deleteByPrimaryKeys(@Param("userId") Integer userId, @Param("answerId") Integer answerId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserAnswerAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserAnswerAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserAnswerAgree> selectByExample(UserAnswerAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserAnswerAgree selectByPrimaryKey(@Param("userId") Integer userId, @Param("answerId") Integer answerId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserAnswerAgree record, @Param("example") UserAnswerAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserAnswerAgree record, @Param("example") UserAnswerAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserAnswerAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_answer_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserAnswerAgree record);
}