package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserTipoffs;
import com.ayue.sp.db.po.UserTipoffsExample;

@Repository
public interface UserTipoffsMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        long countByExample(UserTipoffsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        int deleteByExample(UserTipoffsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        int deleteByPrimaryKey(@Param("targetUserId") Integer targetUserId, @Param("userId") Integer userId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        int insert(UserTipoffs record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        int insertSelective(UserTipoffs record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        List<UserTipoffs> selectByExample(UserTipoffsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        UserTipoffs selectByPrimaryKey(@Param("targetUserId") Integer targetUserId, @Param("userId") Integer userId);
        UserTipoffs selectByPrimary(@Param("targetUserId") Integer targetUserId, @Param("userId") Integer userId,@Param("type") byte type);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserTipoffs record, @Param("example") UserTipoffsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        int updateByExample(@Param("record") UserTipoffs record, @Param("example") UserTipoffsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        int updateByPrimaryKeySelective(UserTipoffs record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_tipoffs
         * @mbg.generated  Thu Oct 08 14:32:45 CST 2020
         */
        int updateByPrimaryKey(UserTipoffs record);
        int getUserTipoffsCount();
        void dealedTipoff(@Param("userId")int userId,@Param("targetUserId")int targetUserId);
}