package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserCashout;
import com.ayue.sp.db.po.UserCashoutExample;

@Repository
public interface UserCashoutMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserCashoutExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserCashoutExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(String partnerTradeNo);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserCashout record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserCashout record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserCashout> selectByExample(UserCashoutExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserCashout selectByPrimaryKey(String partnerTradeNo);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserCashout record, @Param("example") UserCashoutExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserCashout record, @Param("example") UserCashoutExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserCashout record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_cashout
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserCashout record);
        int getUserCashoutCount();
        List<UserCashout> getUserCashoutByUserIds(List<Integer> userIds);
}