package com.ayue.sp.db.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserLoginRecord;
import com.ayue.sp.db.po.UserLoginRecordExample;

@Repository
public interface UserLoginRecordMapper {

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        long countByExample(UserLoginRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        int deleteByExample(UserLoginRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("loginTime") Date loginTime);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        int insert(UserLoginRecord record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        int insertSelective(UserLoginRecord record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        List<UserLoginRecord> selectByExample(UserLoginRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        UserLoginRecord selectByPrimaryKey(@Param("userId") Integer userId, @Param("loginTime") Date loginTime);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserLoginRecord record, @Param("example") UserLoginRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        int updateByExample(@Param("record") UserLoginRecord record, @Param("example") UserLoginRecordExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        int updateByPrimaryKeySelective(UserLoginRecord record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_login_record
         * 
         * @mbg.generated Wed Oct 07 16:43:44 CST 2020
         */
        int updateByPrimaryKey(UserLoginRecord record);
}