package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserBrowse;
import com.ayue.sp.db.po.UserBrowseExample;

@Repository
public interface UserBrowseMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserBrowseExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserBrowseExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("questionId") Integer questionId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserBrowse record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserBrowse record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserBrowse> selectByExample(UserBrowseExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserBrowse selectByPrimaryKey(@Param("userId") Integer userId, @Param("questionId") Integer questionId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserBrowse record, @Param("example") UserBrowseExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserBrowse record, @Param("example") UserBrowseExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserBrowse record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_browse
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserBrowse record);

        int replace(UserBrowse record);
}