package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserVote;
import com.ayue.sp.db.po.UserVoteExample;

@Repository
public interface UserVoteMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserVoteExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserVoteExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserVote record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserVote record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserVote> selectByExample(UserVoteExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserVote selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserVote record, @Param("example") UserVoteExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserVote record, @Param("example") UserVoteExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserVote record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_vote
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserVote record);

        int getUserVoteCount();
}