package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.User2visited;
import com.ayue.sp.db.po.User2visitedExample;

@Repository
public interface User2visitedMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        long countByExample(User2visitedExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        int deleteByExample(User2visitedExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        int deleteByPrimaryKey(@Param("questionId") Integer questionId, @Param("targetUserId") Integer targetUserId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        int insert(User2visited record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        int insertSelective(User2visited record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        List<User2visited> selectByExample(User2visitedExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        User2visited selectByPrimaryKey(@Param("questionId") Integer questionId, @Param("targetUserId") Integer targetUserId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        int updateByExampleSelective(@Param("record") User2visited record, @Param("example") User2visitedExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        int updateByExample(@Param("record") User2visited record, @Param("example") User2visitedExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        int updateByPrimaryKeySelective(User2visited record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2visited
         * @mbg.generated  Wed Oct 07 19:22:07 CST 2020
         */
        int updateByPrimaryKey(User2visited record);

        int batchInsert(List<User2visited> user2visiteds);
        List<User2visited> getUser2visited(@Param("questionId")int questionId,@Param("targetUserId") int targetUserId);
        User2visited getUser2visitedByQuestion(@Param("questionId")int questionId,@Param("targetUserId") int targetUserId,@Param("userId") int userId,@Param("type") int type);


}