package com.ayue.sp.db.dao;

import java.util.List;
import java.util.Map;

import com.ayue.sp.db.po.User2visited;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.User;
import com.ayue.sp.db.po.UserExample;

@Repository
public interface UserMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        long countByExample(UserExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int deleteByExample(UserExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int insert(User record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int insertSelective(User record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        List<User> selectByExample(UserExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        User selectByPrimaryKey(Integer id);
        Integer selectByEnergyBean(Integer id);

        List<Integer> getUserLables(String labels);

        List<Integer> getUserLablesByLables(String labels);
        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int updateByExample(@Param("record") User record, @Param("example") UserExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int updateByPrimaryKeySelective(User record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user
         * @mbg.generated  Wed Oct 07 14:57:35 CST 2020
         */
        int updateByPrimaryKey(User record);

        int resetDayTicket();
        int updateRank(List<User> users);

        int resetWeekTicket();

        int getMaxUserId();

        int batchUpdateHistory(List<User> users);

        void addForwardCount(Integer userId);

        List<User> getUserName(List<Integer> collect);
        User getUserLogin(@Param("name")String userName,@Param("password")String password);
        void updateUserTicket(@Param("ticket")Integer ticket,@Param("userId")Integer userId);
}