package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserConvert;
import com.ayue.sp.db.po.UserConvertExample;

@Repository
public interface UserConvertMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserConvertExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserConvertExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserConvert record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserConvert record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserConvert> selectByExample(UserConvertExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserConvert selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserConvert record, @Param("example") UserConvertExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserConvert record, @Param("example") UserConvertExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserConvert record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_convert
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserConvert record);
}