package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserQuestionCollection;
import com.ayue.sp.db.po.UserQuestionCollectionExample;

@Repository
public interface UserQuestionCollectionMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserQuestionCollectionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserQuestionCollectionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("questionId") Integer questionId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserQuestionCollection record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserQuestionCollection record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserQuestionCollection> selectByExample(UserQuestionCollectionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserQuestionCollection selectByPrimaryKey(@Param("userId") Integer userId, @Param("questionId") Integer questionId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserQuestionCollection record, @Param("example") UserQuestionCollectionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserQuestionCollection record, @Param("example") UserQuestionCollectionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserQuestionCollection record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_question_collection
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserQuestionCollection record);
        void deleteByPrimaryKeys(@Param("userId") Integer userId, @Param("questionId") Integer questionId);
}