package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserAttention;
import com.ayue.sp.db.po.UserAttentionExample;

@Repository
public interface UserAttentionMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserAttentionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserAttentionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("attentionUserId") Integer attentionUserId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserAttention record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserAttention record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserAttention> selectByExample(UserAttentionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserAttention selectByPrimaryKey(@Param("userId") Integer userId, @Param("attentionUserId") Integer attentionUserId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserAttention record, @Param("example") UserAttentionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserAttention record, @Param("example") UserAttentionExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserAttention record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_attention
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserAttention record);
}