package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserRecharge;
import com.ayue.sp.db.po.UserRechargeExample;

@Repository
public interface UserRechargeMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserRechargeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserRechargeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(String outTradeNo);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserRecharge record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserRecharge record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserRecharge> selectByExample(UserRechargeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserRecharge selectByPrimaryKey(String outTradeNo);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserRecharge record, @Param("example") UserRechargeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserRecharge record, @Param("example") UserRechargeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserRecharge record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_recharge
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserRecharge record);

        Integer getUserRechargeCount();
        void updateStatus(String outTradeNo);
        void updateByStatus(String outTradeNo);
}