package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserQuestionForward;
import com.ayue.sp.db.po.UserQuestionForwardExample;

@Repository
public interface UserQuestionForwardMapper {
        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        long countByExample(UserQuestionForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int deleteByExample(UserQuestionForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("questionId") Integer questionId);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int insert(UserQuestionForward record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int insertSelective(UserQuestionForward record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        List<UserQuestionForward> selectByExample(UserQuestionForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        UserQuestionForward selectByPrimaryKey(@Param("userId") Integer userId, @Param("questionId") Integer questionId);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserQuestionForward record, @Param("example") UserQuestionForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int updateByExample(@Param("record") UserQuestionForward record, @Param("example") UserQuestionForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int updateByPrimaryKeySelective(UserQuestionForward record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_question_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int updateByPrimaryKey(UserQuestionForward record);
}