package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserReplyAgree;
import com.ayue.sp.db.po.UserReplyAgreeExample;

@Repository
public interface UserReplyAgreeMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserReplyAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserReplyAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("replyId") Integer replyId);
        void deleteByPrimaryKeys(@Param("userId") Integer userId, @Param("replyId") Integer replyId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserReplyAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserReplyAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserReplyAgree> selectByExample(UserReplyAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserReplyAgree selectByPrimaryKey(@Param("userId") Integer userId, @Param("replyId") Integer replyId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserReplyAgree record, @Param("example") UserReplyAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserReplyAgree record, @Param("example") UserReplyAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserReplyAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_reply_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserReplyAgree record);
}