package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserAnswerForward;
import com.ayue.sp.db.po.UserAnswerForwardExample;

@Repository
public interface UserAnswerForwardMapper {
        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        long countByExample(UserAnswerForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int deleteByExample(UserAnswerForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("answerId") Integer answerId);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int insert(UserAnswerForward record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int insertSelective(UserAnswerForward record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        List<UserAnswerForward> selectByExample(UserAnswerForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        UserAnswerForward selectByPrimaryKey(@Param("userId") Integer userId, @Param("answerId") Integer answerId);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserAnswerForward record, @Param("example") UserAnswerForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int updateByExample(@Param("record") UserAnswerForward record, @Param("example") UserAnswerForwardExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int updateByPrimaryKeySelective(UserAnswerForward record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table user_answer_forward
         *
         * @mbg.generated Thu Oct 08 15:48:42 CST 2020
         */
        int updateByPrimaryKey(UserAnswerForward record);
}