package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserCommentAgree;
import com.ayue.sp.db.po.UserCommentAgreeExample;

@Repository
public interface UserCommentAgreeMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(UserCommentAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(UserCommentAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("commentId") Integer commentId);
        void deleteByPrimaryKeys(@Param("userId") Integer userId, @Param("commentId") Integer commentId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(UserCommentAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(UserCommentAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<UserCommentAgree> selectByExample(UserCommentAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        UserCommentAgree selectByPrimaryKey(@Param("userId") Integer userId, @Param("commentId") Integer commentId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserCommentAgree record, @Param("example") UserCommentAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") UserCommentAgree record, @Param("example") UserCommentAgreeExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(UserCommentAgree record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_comment_agree
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(UserCommentAgree record);

}