package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.UserNews;
import com.ayue.sp.db.po.UserNewsExample;

@Repository
public interface UserNewsMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        long countByExample(UserNewsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        int deleteByExample(UserNewsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        int deleteByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        int insert(UserNews record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        int insertSelective(UserNews record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        List<UserNews> selectByExample(UserNewsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        UserNews selectByPrimaryKey(Integer id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        int updateByExampleSelective(@Param("record") UserNews record, @Param("example") UserNewsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        int updateByExample(@Param("record") UserNews record, @Param("example") UserNewsExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        int updateByPrimaryKeySelective(UserNews record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user_news
         * @mbg.generated  Thu Oct 08 14:34:35 CST 2020
         */
        int updateByPrimaryKey(UserNews record);

        List<UserNews> getChat(Integer[] chatId);
        void updateChatStatus(Integer[] chatId);
        void delReadChat(Integer[] chatId);
}