package com.ayue.sp.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.sp.db.po.User2subject;
import com.ayue.sp.db.po.User2subjectExample;

@Repository
public interface User2subjectMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        long countByExample(User2subjectExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByExample(User2subjectExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("subjectId") Integer subjectId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insert(User2subject record);

        void delSubjectMember(@Param("subjectId") Integer subjectId,@Param("userId") Integer userId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int insertSelective(User2subject record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        List<User2subject> selectByExample(User2subjectExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        User2subject selectByPrimaryKey(@Param("userId") Integer userId, @Param("subjectId") Integer subjectId);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExampleSelective(@Param("record") User2subject record, @Param("example") User2subjectExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByExample(@Param("record") User2subject record, @Param("example") User2subjectExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKeySelective(User2subject record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table user2subject
         * @mbg.generated  Sat Sep 12 20:14:38 CST 2020
         */
        int updateByPrimaryKey(User2subject record);
}